# generated by datamodel-codegen:
#   filename:  commands/history/create-version-restore-task.json

from __future__ import annotations

from uuid import UUID

from pydantic import BaseModel, ConfigDict, Field

from ...queries.tasks import list_tasks


class CreateVersionRestoreTaskResponse(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    taskId: UUID = Field(..., title="TaskId")
    task: list_tasks.TaskSummary
