# generated by datamodel-codegen:
#   filename:  commands/history/create-named-version.json

from __future__ import annotations

from uuid import UUID

from pydantic import BaseModel, ConfigDict, Field, conint, constr


class CreateNamedVersion(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    resourceId: UUID = Field(..., title="UserId")
    label: constr(min_length=1, max_length=120)
    baseJournalSeq: conint(ge=1)
    idempotencyKey: UUID = Field(..., title="IdempotencyKey")


class CreateNamedVersionResponse(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    resourceId: UUID = Field(..., title="UserId")
    versionId: UUID = Field(..., title="UserId")
    label: str
    baseJournalSeq: int
