# generated by datamodel-codegen:
#   filename:  commands/history/restore-version.json

from __future__ import annotations

from uuid import UUID

from pydantic import BaseModel, ConfigDict, Field, conint


class RestoreVersion(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    baseJournalSeq: conint(ge=1)


class RestoreVersionResponse(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    resourceId: UUID = Field(..., title="UserId")
    newSeq: int
    label: str
