# generated by datamodel-codegen:
#   filename:  events/permission/permission-changed.json

from __future__ import annotations

from enum import Enum
from uuid import UUID

from pydantic import AwareDatetime, BaseModel, ConfigDict, Field, constr


class ScopeType(Enum):
    workspace = "workspace"
    project = "project"
    resource = "resource"


class Role(Enum):
    Owner = "Owner"
    Manage = "Manage"
    Edit = "Edit"
    Comment = "Comment"
    Read = "Read"
    Member = "Member"
    NoneType_None = None


class PermissionChanged(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    scopeType: ScopeType
    scopeId: UUID
    workspaceId: UUID = Field(..., title="WorkspaceId")
    accountId: UUID | None = Field(None, title="UserId")
    action: constr(min_length=1)
    role: Role | None = None
    occurredAt: AwareDatetime
