from __future__ import annotations

from datetime import datetime
from typing import Protocol
from uuid import UUID

from app_core.import_export.domain import ExportSession, ImportSession
from app_core.resource.domain import Resource, ResourceContent


class ImportExportSessionRepository(Protocol):
    async def create_import(self, session: ImportSession) -> ImportSession: ...

    async def get_import(self, import_id: UUID) -> ImportSession | None: ...

    async def get_import_by_task(self, task_id: UUID) -> ImportSession | None: ...

    async def save_import(self, session: ImportSession) -> None: ...

    async def expired_imports(
        self, now: datetime, *, limit: int
    ) -> list[ImportSession]: ...

    async def completed_imports(self, *, limit: int) -> list[ImportSession]: ...

    async def delete_import(self, import_id: UUID) -> None: ...

    async def create_export(self, session: ExportSession) -> ExportSession: ...

    async def get_export(self, export_id: UUID) -> ExportSession | None: ...

    async def get_export_by_task(self, task_id: UUID) -> ExportSession | None: ...

    async def save_export(self, session: ExportSession) -> None: ...

    async def expired_exports(
        self, now: datetime, *, limit: int
    ) -> list[ExportSession]: ...

    async def delete_export(self, export_id: UUID) -> None: ...


class TemporaryAssetStore(Protocol):
    async def put_import_source(self, asset_id: UUID, data: bytes) -> None: ...

    async def get_import_source(self, asset_id: UUID) -> bytes: ...

    async def delete_import_source(self, asset_id: UUID) -> None: ...

    async def put_export_result(self, asset_id: UUID, data: bytes) -> None: ...

    async def get_export_result(self, asset_id: UUID) -> bytes: ...

    async def delete_export_result(self, asset_id: UUID) -> None: ...


class ResourceExportSnapshotRepository(Protocol):
    async def read(
        self, resource_id: UUID
    ) -> tuple[Resource, ResourceContent] | None: ...
