# generated by datamodel-codegen:
#   filename:  commands/webhooks/requeue-deliveries.json

from __future__ import annotations

from uuid import UUID

from pydantic import BaseModel, ConfigDict, Field


class RequeueWebhookDeliveries(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    webhookId: UUID = Field(..., title="UserId")


class RequeueWebhookDeliveriesResponse(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    requeued: int
    remainingFailed: int
