# generated by datamodel-codegen:
#   filename:  queries/permission/get-resource-capabilities.json

from __future__ import annotations

from uuid import UUID

from pydantic import BaseModel, ConfigDict, Field


class GetResourceCapabilitiesResponse(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    resourceId: UUID = Field(..., title="ResourceId")
    canRead: bool
    canUpdate: bool
    canComment: bool
    canManage: bool
    canResolveCommentThread: bool
    canReopenCommentThread: bool
