# generated by datamodel-codegen:
#   filename:  queries/permission/has-sole-workspace-ownership.json

from __future__ import annotations

from uuid import UUID

from pydantic import BaseModel, ConfigDict


class HasSoleWorkspaceOwnershipResponse(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    hasSoleWorkspaceOwnership: bool
    workspaceId: UUID | None
