# generated by datamodel-codegen:
#   filename:  queries/permission/list-resource-share-links.json

from __future__ import annotations

from enum import Enum
from typing import Literal
from uuid import UUID

from pydantic import AwareDatetime, BaseModel, ConfigDict, Field


class Status(Enum):
    Active = "Active"
    Revoked = "Revoked"
    Expired = "Expired"


class ShareLinkMetadata(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    shareId: UUID = Field(..., title="ShareId")
    resourceId: UUID = Field(..., title="ResourceId")
    capability: Literal["Read"]
    status: Status
    expiresAt: AwareDatetime | None
    createdBy: UUID = Field(..., title="UserId")
    createdAt: AwareDatetime
    revokedAt: AwareDatetime | None


class ListResourceShareLinksResponse(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    resourceId: UUID = Field(..., title="ResourceId")
    shareLinks: list[ShareLinkMetadata]
