# generated by datamodel-codegen:
#   filename:  queries/permission/list-project-members.json

from __future__ import annotations

from enum import Enum
from uuid import UUID

from pydantic import AwareDatetime, BaseModel, ConfigDict, Field


class Role(Enum):
    Owner = "Owner"
    Manage = "Manage"
    Edit = "Edit"
    Comment = "Comment"
    Read = "Read"


class MembershipKind(Enum):
    Owner = "Owner"
    Member = "Member"


class Member(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    projectId: UUID = Field(..., title="ProjectId")
    accountId: UUID = Field(..., title="UserId")
    email: str
    role: Role
    membershipKind: MembershipKind
    createdAt: AwareDatetime
    updatedAt: AwareDatetime


class ListProjectMembersResponse(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    members: list[Member]
