# generated by datamodel-codegen:
#   filename:  queries/permission/list-workspace-invitations.json

from __future__ import annotations

from enum import Enum
from typing import Literal
from uuid import UUID

from pydantic import AwareDatetime, BaseModel, ConfigDict, EmailStr, Field


class State(Enum):
    Pending = "Pending"
    Accepted = "Accepted"
    Expired = "Expired"
    Revoked = "Revoked"


class Invitation(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    invitationId: UUID = Field(..., title="InvitationId")
    workspaceId: UUID = Field(..., title="WorkspaceId")
    targetEmail: EmailStr
    targetAccountId: UUID | None = None
    role: Literal["Member"]
    state: State
    expiresAt: AwareDatetime
    createdBy: UUID = Field(..., title="UserId")
    createdAt: AwareDatetime
    acceptedAt: AwareDatetime | None = None


class ListWorkspaceInvitationsResponse(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    invitations: list[Invitation]
