# generated by datamodel-codegen:
#   filename:  queries/permission/list-workspace-members.json

from __future__ import annotations

from enum import Enum
from uuid import UUID

from pydantic import AwareDatetime, BaseModel, ConfigDict, Field


class MembershipKind(Enum):
    Owner = "Owner"
    Member = "Member"


class Member(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    accountId: UUID = Field(..., title="UserId")
    email: str
    membershipKind: MembershipKind
    createdAt: AwareDatetime


class ListWorkspaceMembersResponse(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    members: list[Member]
