# generated by datamodel-codegen:
#   filename:  queries/permission/list-resource-permissions.json

from __future__ import annotations

from enum import Enum
from uuid import UUID

from pydantic import AwareDatetime, BaseModel, ConfigDict, Field


class Role(Enum):
    Owner = "Owner"
    Manage = "Manage"
    Edit = "Edit"
    Comment = "Comment"
    Read = "Read"


class Permission(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    resourceId: UUID = Field(..., title="ResourceId")
    accountId: UUID = Field(..., title="UserId")
    email: str
    role: Role
    createdAt: AwareDatetime
    updatedAt: AwareDatetime


class ListResourcePermissionsResponse(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    permissions: list[Permission]
