# generated by datamodel-codegen:
#   filename:  queries/permission/open-public-shared-resource.json

from __future__ import annotations

from enum import Enum
from typing import Any
from uuid import UUID

from pydantic import BaseModel, ConfigDict, Field, conint


class ResourceType(Enum):
    document = "document"
    code = "code"
    markdown = "markdown"
    text = "text"


class OpenPublicSharedResourceResponse(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    resourceId: UUID = Field(..., title="ResourceId")
    name: str
    resourceType: ResourceType
    snapshot: dict[str, Any] | None
    journalSeq: conint(ge=0)
