# generated by datamodel-codegen:
#   filename:  queries/notifications/list-notifications.json

from __future__ import annotations

from typing import Any
from uuid import UUID

from pydantic import BaseModel, ConfigDict, Field


class Item(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    notificationId: UUID = Field(..., title="UserId")
    kind: str
    targetRef: dict[str, Any] | None = None
    payload: dict[str, Any]
    createdAt: str | None
    readAt: str | None


class ListNotificationsResponse(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    items: list[Item]
    unreadCount: int
