# generated by datamodel-codegen:
#   filename:  queries/search/search-workspace.json

from __future__ import annotations

from enum import Enum
from uuid import UUID

from pydantic import BaseModel, ConfigDict, Field


class ResourceType(Enum):
    document = "document"
    code = "code"
    markdown = "markdown"
    text = "text"


class Item(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    resourceId: UUID = Field(..., title="UserId")
    projectId: UUID | None = Field(None, title="ProjectId")
    folderId: UUID | None = None
    name: str
    resourceType: ResourceType
    score: float
    snippet: str | None = None


class SearchWorkspaceResponse(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    workspaceId: UUID = Field(..., title="WorkspaceId")
    query: str
    items: list[Item]
