# generated by datamodel-codegen:
#   filename:  queries/search/search-history.json

from __future__ import annotations

from pydantic import BaseModel, ConfigDict


class Item(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    query: str
    lastUsedAt: str | None


class SearchHistoryResponse(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    items: list[Item]
