# generated by datamodel-codegen:
#   filename:  queries/search/search-suggestions.json

from __future__ import annotations

from uuid import UUID

from pydantic import BaseModel, ConfigDict, Field


class SearchSuggestionsResponse(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    workspaceId: UUID = Field(..., title="WorkspaceId")
    prefix: str
    suggestions: list[str]
