# generated by datamodel-codegen:
#   filename:  queries/search/search-comments.json

from __future__ import annotations

from uuid import UUID

from pydantic import BaseModel, ConfigDict, Field


class Item(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    commentId: UUID = Field(..., title="UserId")
    threadId: UUID = Field(..., title="UserId")
    resourceId: UUID = Field(..., title="UserId")
    resourceName: str
    body: str


class SearchCommentsResponse(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    workspaceId: UUID = Field(..., title="WorkspaceId")
    query: str
    items: list[Item]
