# generated by datamodel-codegen:
#   filename:  queries/webhook/list-webhooks.json

from __future__ import annotations

from uuid import UUID

from pydantic import BaseModel, ConfigDict, Field


class Item(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    subscriptionId: UUID = Field(..., title="UserId")
    url: str
    status: str
    createdAt: str | None


class ListWebhooksResponse(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    workspaceId: UUID = Field(..., title="WorkspaceId")
    items: list[Item]
