/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
	"/v1/auth/register": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/** Register a new account with email + password (FR-AUTH-001) */
		post: operations["RegisterWithEmail"];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/v1/auth/verify-email": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/** Verify email via single-use token (FR-AUTH-002) */
		post: operations["VerifyEmail"];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/v1/auth/resend-verification": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/** Resend email verification (FR-AUTH-004) */
		post: operations["ResendEmailVerification"];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/v1/auth/login": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/** Login with email + password (FR-AUTH-006) */
		post: operations["LoginWithPassword"];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/v1/auth/logout": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/** Logout current device session (FR-AUTH-020, no request body) */
		post: operations["Logout"];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/v1/auth/me": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** Get the actor's own account (FR-AUTH-022) */
		get: operations["GetCurrentAccount"];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/v1/auth/session": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** Get the current device session (FR-AUTH-022) */
		get: operations["GetCurrentSession"];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/v1/auth/forgot-password": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/** Request password reset (FR-AUTH-024) */
		post: operations["RequestPasswordReset"];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/v1/auth/reset-password": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/** Reset password with single-use token (FR-AUTH-025) */
		post: operations["ResetPassword"];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/v1/auth/reauthenticate": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/** Re-verify password for recent authentication (FR-AUTH-034) */
		post: operations["Reauthenticate"];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/v1/auth/delete-account": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/** Request account deletion (FR-AUTH-029/030, no request body) */
		post: operations["RequestAccountDeletion"];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/v1/auth/cancel-delete-account": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/** Cancel a pending account deletion (FR-AUTH-031, no request body) */
		post: operations["CancelAccountDeletion"];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/v1/auth/status": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/**
		 * Get the actor's account lifecycle status and deletion window (FR-AUTH-030/032)
		 * @description Client Query of the Account Recovery Mode view (deletion state, remaining grace period, scheduled final deletion). Registered in contracts/registry.yaml and projected in both language contract packages; the route described here is the HTTP surface for the existing Client Query.
		 */
		get: operations["GetAccountStatus"];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
}
export type webhooks = Record<string, never>;
export interface components {
	schemas: {
		/**
		 * RegisterWithEmail
		 * @description FR-AUTH-001. Request root = email + password. Password length 12-128 per PRD FR-AUTH-001 / OQ-3 (reject common/leaked passwords at the application layer). Response is the anti-enumeration uniform payload (PRD FR-AUTH-005/007, BDD 'two requests get identical external hint'); the auto-established session (BDD FR-AUTH-001, PRD AC-001.1) is delivered as a Secure/HttpOnly Set-Cookie, modeled in OpenAPI, NOT in this body.
		 */
		"register-with-email.schema": {
			/** Format: email */
			email: string;
			password: string;
			$defs: {
				/** RegisterWithEmailResponse */
				RegisterWithEmailResponse: {
					messageKey: string;
					/** Format: email */
					email: string;
				};
			};
		};
		/** RegisterWithEmailResponse */
		RegisterWithEmailResponse: {
			messageKey: string;
			/** Format: email */
			email: string;
		};
		/**
		 * RequestId
		 * Format: uuid
		 */
		RequestId: string;
		/** FieldError */
		FieldError: {
			/** FieldName */
			field: string;
			/** FieldErrorCode */
			code: string;
			/** FieldMessage */
			message: string;
		};
		/**
		 * ErrorEnvelope
		 * @description Canonical error envelope (doc 28 §29). The root object IS the envelope; it is referenced directly by OpenAPI error responses. category is one of the ten canonical categories from doc 04 §23 / Constitution §3.19; errorCode matches ^[A-Z0-9_]+$; requestId is a UUIDv7; fieldErrors carries field-level validation detail.
		 */
		"error-envelope.schema": {
			/**
			 * AuthErrorCategory
			 * @enum {string}
			 */
			category:
				| "Validation"
				| "Authentication"
				| "Permission"
				| "NotFound"
				| "Conflict"
				| "RateLimit"
				| "Timeout"
				| "DependencyFailure"
				| "Unavailable"
				| "Internal";
			/** ErrorCode */
			errorCode: string;
			/** MessageKey */
			messageKey: string;
			/** ErrorMessage */
			message?: string;
			requestId: components["schemas"]["RequestId"];
			/** Retryable */
			retryable: boolean;
			/** FieldErrors */
			fieldErrors?: components["schemas"]["FieldError"][];
			/**
			 * ErrorDetails
			 * @description Safe, structured business detail only. Must never contain stack traces, SQL, internal hosts, secrets or provider tokens (doc 28 §31).
			 */
			details?: {
				[key: string]: unknown;
			};
			$defs: {
				/** FieldError */
				FieldError: {
					/** FieldName */
					field: string;
					/** FieldErrorCode */
					code: string;
					/** FieldMessage */
					message: string;
				};
			};
		};
		/**
		 * AccountStatusValue
		 * @enum {string}
		 */
		AccountStatusValue:
			| "PendingVerification"
			| "Active"
			| "Disabled"
			| "DeletionPending"
			| "Deleted";
		/**
		 * VerifyEmail
		 * @description FR-AUTH-002. Single-use, 24h verification token in the request body, marked x-sensitive (doc 28 §57). Token is never echoed in the response (doc 28 §58).
		 */
		"verify-email.schema": {
			token: string;
			$defs: {
				/** VerifyEmailResponse */
				VerifyEmailResponse: {
					messageKey: string;
					accountStatus: components["schemas"]["AccountStatusValue"];
				};
			};
		};
		/** VerifyEmailResponse */
		VerifyEmailResponse: {
			messageKey: string;
			accountStatus: components["schemas"]["AccountStatusValue"];
		};
		/**
		 * ResendEmailVerification
		 * @description FR-AUTH-004. Rate-limited (60s cooldown, max 5 per 24h). The response exposes nextAllowedAt so the client can show the 60s countdown (BDD AC-004.3) without leaking account existence: the same payload is returned whether or not the email is registered.
		 */
		"resend-email-verification.schema": {
			/** Format: email */
			email: string;
			$defs: {
				/** ResendEmailVerificationResponse */
				ResendEmailVerificationResponse: {
					messageKey: string;
					/** Format: date-time */
					nextAllowedAt: string;
				};
			};
		};
		/** ResendEmailVerificationResponse */
		ResendEmailVerificationResponse: {
			messageKey: string;
			/** Format: date-time */
			nextAllowedAt: string;
		};
		/**
		 * UserId
		 * Format: uuid
		 */
		UserId: string;
		/**
		 * SessionId
		 * Format: uuid
		 */
		SessionId: string;
		/**
		 * SessionStatusValue
		 * @enum {string}
		 */
		SessionStatusValue:
			| "Active"
			| "Replaced"
			| "LoggedOut"
			| "Expired"
			| "Revoked";
		/** SessionSummary */
		SessionSummary: {
			sessionId: components["schemas"]["SessionId"];
			/** Format: date-time */
			createdAt: string;
			/** Format: date-time */
			lastSeenAt: string;
			/** Format: date-time */
			expiresAt: string;
			currentDevice: boolean;
			status: components["schemas"]["SessionStatusValue"];
			/** Format: date-time */
			lastStrongAuthAt?: string | null;
		};
		/**
		 * LoginWithPassword
		 * @description FR-AUTH-006. Response carries account status, the current session summary, and whether the caller is forced into Account Recovery Mode (PRD FR-AUTH-032: DeletionPending -> recovery mode only). The session credential is delivered as a Secure/HttpOnly Set-Cookie (modeled in OpenAPI), not in this body.
		 */
		"login-with-password.schema": {
			/** Format: email */
			email: string;
			password: string;
			$defs: {
				/** LoginWithPasswordResponse */
				LoginWithPasswordResponse: {
					accountId: components["schemas"]["UserId"];
					accountStatus: components["schemas"]["AccountStatusValue"];
					session: components["schemas"]["SessionSummary"];
					recoveryModeRequired: boolean;
				};
				/** SessionSummary */
				SessionSummary: {
					sessionId: components["schemas"]["SessionId"];
					/** Format: date-time */
					createdAt: string;
					/** Format: date-time */
					lastSeenAt: string;
					/** Format: date-time */
					expiresAt: string;
					currentDevice: boolean;
					status: components["schemas"]["SessionStatusValue"];
					/** Format: date-time */
					lastStrongAuthAt?: string | null;
				};
			};
		};
		/** LoginWithPasswordResponse */
		LoginWithPasswordResponse: {
			accountId: components["schemas"]["UserId"];
			accountStatus: components["schemas"]["AccountStatusValue"];
			session: components["schemas"]["SessionSummary"];
			recoveryModeRequired: boolean;
		};
		/**
		 * LogoutStatusValue
		 * @enum {string}
		 */
		LogoutStatusValue: "LoggedOut" | "AlreadyLoggedOut";
		/**
		 * LogoutResponse
		 * @description Logout is a no-body Command (registry requestBody: none, doc 28 §8): the client sends no request body and OpenAPI declares no requestBody, so this file's root is the Response and no request schema exists. FR-AUTH-020; idempotent, so sessionStatus = AlreadyLoggedOut when the session was already invalid (BDD 'logout is idempotent').
		 */
		"logout.schema": {
			messageKey: string;
			sessionStatus: components["schemas"]["LogoutStatusValue"];
			$defs: {
				/**
				 * LogoutStatusValue
				 * @enum {string}
				 */
				LogoutStatusValue: "LoggedOut" | "AlreadyLoggedOut";
			};
		};
		/**
		 * GetCurrentAccountResponse
		 * @description FR-AUTH-022. Only the actor's own account facts. Per doc 16 §66 the Auth module must NOT answer Permission questions, so no capability enumeration is included (capability answers belong to doc 07); canCreateWorkspace is a status-derived product boolean, not a Permission capability set. This Query has no request body (registry requestBody: none, doc 28 §8): the client sends no request body, so this file's root is the Response and no request schema exists.
		 */
		"get-current-account.schema": {
			accountId: components["schemas"]["UserId"];
			/** Format: email */
			primaryEmail: string;
			accountStatus: components["schemas"]["AccountStatusValue"];
			/** Format: date-time */
			emailVerifiedAt: string | null;
			/** Format: date-time */
			createdAt: string;
			canCreateWorkspace: boolean;
			inAccountRecoveryMode: boolean;
		};
		/**
		 * GetCurrentSessionResponse
		 * @description FR-AUTH-022. Must identify 'this is the current device' (BDD FR-AUTH-022: creation time + current device marker). currentDevice is always true for this endpoint since it returns the caller's own active session. This Query has no request body (registry requestBody: none, doc 28 §8): the client sends no request body, so this file's root is the Response and no request schema exists.
		 */
		"get-current-session.schema": {
			sessionId: components["schemas"]["SessionId"];
			/** Format: date-time */
			createdAt: string;
			/** Format: date-time */
			lastSeenAt: string;
			/** Format: date-time */
			expiresAt: string;
			currentDevice: boolean;
			status: components["schemas"]["SessionStatusValue"];
			/** Format: date-time */
			lastStrongAuthAt?: string | null;
		};
		/**
		 * RequestPasswordReset
		 * @description FR-AUTH-024. Anti-enumeration: identical external response whether or not the email is registered (PRD FR-AUTH-007). Rate-limited (AC-024.3). The request carries only the email; the reset link is delivered out-of-band.
		 */
		"request-password-reset.schema": {
			/** Format: email */
			email: string;
			$defs: {
				/** RequestPasswordResetResponse */
				RequestPasswordResetResponse: {
					messageKey: string;
					/** Format: date-time */
					nextAllowedAt: string;
				};
			};
		};
		/** RequestPasswordResetResponse */
		RequestPasswordResetResponse: {
			messageKey: string;
			/** Format: date-time */
			nextAllowedAt: string;
		};
		/**
		 * ResetPassword
		 * @description FR-AUTH-025/026/027. Single-use, 15-minute reset token in the request body, marked x-sensitive (doc 28 §57). Token is never echoed in the response. On success all old sessions are invalidated and no new session is auto-created (PRD FR-AUTH-027).
		 */
		"reset-password.schema": {
			token: string;
			newPassword: string;
			$defs: {
				/** ResetPasswordResponse */
				ResetPasswordResponse: {
					messageKey: string;
					accountStatus: components["schemas"]["AccountStatusValue"];
				};
			};
		};
		/** ResetPasswordResponse */
		ResetPasswordResponse: {
			messageKey: string;
			accountStatus: components["schemas"]["AccountStatusValue"];
		};
		/**
		 * Reauthenticate
		 * @description FR-AUTH-034 / doc 16 §104-§105. Re-verify the password before high-risk operations (10-minute recent-auth window). Request = password (x-sensitive). Response expresses the window: reauthenticatedAt and validUntil (= reauthenticatedAt + 10m).
		 */
		"reauthenticate.schema": {
			password: string;
			$defs: {
				/** ReauthenticateResponse */
				ReauthenticateResponse: {
					messageKey: string;
					/** Format: date-time */
					reauthenticatedAt: string;
					/** Format: date-time */
					validUntil: string;
					windowSeconds: number;
				};
			};
		};
		/** ReauthenticateResponse */
		ReauthenticateResponse: {
			messageKey: string;
			/** Format: date-time */
			reauthenticatedAt: string;
			/** Format: date-time */
			validUntil: string;
			windowSeconds: number;
		};
		/**
		 * RequestAccountDeletionResponse
		 * @description RequestAccountDeletion is a no-body Command (registry requestBody: none, doc 28 §8): the client sends no request body and OpenAPI declares no requestBody, so this file's root is the Response and no request schema exists. The recent-authentication requirement (10-minute window, FR-AUTH-034) is satisfied by the session's lastStrongAuthAt, never by a request field. FR-AUTH-029/030; the response exposes the 30-day grace window (executeAfter = scheduled final deletion).
		 */
		"request-account-deletion.schema": {
			messageKey: string;
			accountStatus: components["schemas"]["AccountStatusValue"];
			/** Format: date-time */
			deletionRequestedAt: string;
			gracePeriodDaysRemaining: number;
			/** Format: date-time */
			executeAfter: string;
		};
		/**
		 * CancelAccountDeletionResponse
		 * @description CancelAccountDeletion is a no-body Command (registry requestBody: none, doc 28 §8): the client sends no request body and OpenAPI declares no requestBody, so this file's root is the Response and no request schema exists. FR-AUTH-031: restore to the pre-deletion status (Active or PendingVerification), userId unchanged; reachable only while the account is DeletionPending, otherwise the AccountNotInDeletion error applies.
		 */
		"cancel-account-deletion.schema": {
			messageKey: string;
			accountStatus: components["schemas"]["AccountStatusValue"];
			/** Format: date-time */
			restoredAt: string;
		};
		/**
		 * GetAccountStatusResponse
		 * @description FR-AUTH-030 AC-030.2 / FR-AUTH-032 AC-032.2. The deletion / recovery-mode view: deletionRequestedAt, gracePeriodDaysRemaining and executeAfter (scheduled final deletion) are null unless the account is DeletionPending. This Query has no request body (registry requestBody: none, doc 28 §8): the client sends no request body, so this file's root is the Response and no request schema exists.
		 */
		"get-account-status.schema": {
			accountStatus: components["schemas"]["AccountStatusValue"];
			inAccountRecoveryMode: boolean;
			/** Format: date-time */
			deletionRequestedAt: string | null;
			gracePeriodDaysRemaining: number | null;
			/** Format: date-time */
			executeAfter: string | null;
			canCancelDeletion: boolean;
		};
	};
	responses: {
		/** @description Canonical error envelope (doc 28 §29) */
		ErrorEnvelopeResponse: {
			headers: {
				[name: string]: unknown;
			};
			content: {
				"application/json": components["schemas"]["error-envelope.schema"];
			};
		};
	};
	parameters: {
		/** @description Stable key for safe retry of a logical mutating command (doc 28 §13) */
		IdempotencyKey: string;
	};
	requestBodies: never;
	headers: never;
	pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
	RegisterWithEmail: {
		parameters: {
			query?: never;
			header?: {
				/** @description Stable key for safe retry of a logical mutating command (doc 28 §13) */
				"Idempotency-Key"?: components["parameters"]["IdempotencyKey"];
			};
			path?: never;
			cookie?: never;
		};
		requestBody: {
			content: {
				"application/json": components["schemas"]["register-with-email.schema"];
			};
		};
		responses: {
			/** @description Account created (anti-enumeration uniform payload) */
			200: {
				headers: {
					/** @description Secure; HttpOnly session cookie for the auto-established session */
					"Set-Cookie"?: string;
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["RegisterWithEmailResponse"];
				};
			};
			400: components["responses"]["ErrorEnvelopeResponse"];
			409: components["responses"]["ErrorEnvelopeResponse"];
			429: components["responses"]["ErrorEnvelopeResponse"];
		};
	};
	VerifyEmail: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody: {
			content: {
				"application/json": components["schemas"]["verify-email.schema"];
			};
		};
		responses: {
			/** @description Email verified */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["VerifyEmailResponse"];
				};
			};
			400: components["responses"]["ErrorEnvelopeResponse"];
			401: components["responses"]["ErrorEnvelopeResponse"];
		};
	};
	ResendEmailVerification: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody: {
			content: {
				"application/json": components["schemas"]["resend-email-verification.schema"];
			};
		};
		responses: {
			/** @description Resend accepted (uniform, no account-existence leak) */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ResendEmailVerificationResponse"];
				};
			};
			400: components["responses"]["ErrorEnvelopeResponse"];
			429: components["responses"]["ErrorEnvelopeResponse"];
		};
	};
	LoginWithPassword: {
		parameters: {
			query?: never;
			header?: {
				/** @description Stable key for safe retry of a logical mutating command (doc 28 §13) */
				"Idempotency-Key"?: components["parameters"]["IdempotencyKey"];
			};
			path?: never;
			cookie?: never;
		};
		requestBody: {
			content: {
				"application/json": components["schemas"]["login-with-password.schema"];
			};
		};
		responses: {
			/** @description Login succeeded; session summary returned */
			200: {
				headers: {
					/** @description Secure; HttpOnly session cookie */
					"Set-Cookie"?: string;
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["LoginWithPasswordResponse"];
				};
			};
			400: components["responses"]["ErrorEnvelopeResponse"];
			401: components["responses"]["ErrorEnvelopeResponse"];
			429: components["responses"]["ErrorEnvelopeResponse"];
		};
	};
	Logout: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Logged out (idempotent) */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["logout.schema"];
				};
			};
			401: components["responses"]["ErrorEnvelopeResponse"];
		};
	};
	GetCurrentAccount: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Current account facts */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["get-current-account.schema"];
				};
			};
			401: components["responses"]["ErrorEnvelopeResponse"];
		};
	};
	GetCurrentSession: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Current session facts */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["get-current-session.schema"];
				};
			};
			401: components["responses"]["ErrorEnvelopeResponse"];
		};
	};
	RequestPasswordReset: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody: {
			content: {
				"application/json": components["schemas"]["request-password-reset.schema"];
			};
		};
		responses: {
			/** @description Reset request accepted (uniform, no account-existence leak) */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["RequestPasswordResetResponse"];
				};
			};
			400: components["responses"]["ErrorEnvelopeResponse"];
			429: components["responses"]["ErrorEnvelopeResponse"];
		};
	};
	ResetPassword: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody: {
			content: {
				"application/json": components["schemas"]["reset-password.schema"];
			};
		};
		responses: {
			/** @description Password reset succeeded */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ResetPasswordResponse"];
				};
			};
			400: components["responses"]["ErrorEnvelopeResponse"];
			401: components["responses"]["ErrorEnvelopeResponse"];
		};
	};
	Reauthenticate: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody: {
			content: {
				"application/json": components["schemas"]["reauthenticate.schema"];
			};
		};
		responses: {
			/** @description Re-authentication window established */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ReauthenticateResponse"];
				};
			};
			400: components["responses"]["ErrorEnvelopeResponse"];
			401: components["responses"]["ErrorEnvelopeResponse"];
		};
	};
	RequestAccountDeletion: {
		parameters: {
			query?: never;
			header?: {
				/** @description Stable key for safe retry of a logical mutating command (doc 28 §13) */
				"Idempotency-Key"?: components["parameters"]["IdempotencyKey"];
			};
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Deletion requested; 30-day grace period started */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["request-account-deletion.schema"];
				};
			};
			401: components["responses"]["ErrorEnvelopeResponse"];
			409: components["responses"]["ErrorEnvelopeResponse"];
		};
	};
	CancelAccountDeletion: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Deletion cancelled; status restored */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["cancel-account-deletion.schema"];
				};
			};
			401: components["responses"]["ErrorEnvelopeResponse"];
			409: components["responses"]["ErrorEnvelopeResponse"];
		};
	};
	GetAccountStatus: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Account status */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["get-account-status.schema"];
				};
			};
			401: components["responses"]["ErrorEnvelopeResponse"];
		};
	};
}
