# generated by datamodel-codegen:
#   filename:  queries/integrations/get-api-usage.json

from __future__ import annotations

from pydantic import BaseModel, ConfigDict


class Item(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    route: str
    requests: int
    limit: int


class GetApiUsageResponse(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    items: list[Item]
