# generated by datamodel-codegen:
#   filename:  events/task/task-progress-updated.json

from __future__ import annotations

from enum import Enum
from typing import Literal
from uuid import UUID

from pydantic import (
    AwareDatetime,
    BaseModel,
    ConfigDict,
    Field,
    confloat,
    conint,
    constr,
)


class State(Enum):
    Created = "Created"
    Queued = "Queued"
    Running = "Running"
    WaitingForUser = "WaitingForUser"
    Retrying = "Retrying"
    Succeeded = "Succeeded"
    PartialSucceeded = "PartialSucceeded"
    Failed = "Failed"
    Cancelled = "Cancelled"


class TaskProgressUpdatedPayload(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    taskId: UUID = Field(..., title="TaskId")
    taskType: constr(min_length=1)
    state: State
    stage: str | None
    messageCode: str | None
    current: conint(ge=0) | None
    total: conint(ge=0) | None
    percentage: confloat(ge=0.0, le=100.0) | None


class TaskProgressUpdated(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    eventId: UUID = Field(..., title="EventId")
    eventType: Literal["TaskProgressUpdated"]
    schemaVersion: constr(pattern=r"^\d+\.\d+\.\d+$")
    occurredAt: AwareDatetime
    producer: constr(min_length=1)
    payload: TaskProgressUpdatedPayload
