# generated by datamodel-codegen:
#   filename:  commands/auth/cancel-account-deletion.json

from __future__ import annotations

from pydantic import AwareDatetime, BaseModel, ConfigDict, constr

from ...ids import ids


class CancelAccountDeletionResponse(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    messageKey: constr(min_length=1)
    accountStatus: ids.AccountStatusValue
    restoredAt: AwareDatetime
