# generated by datamodel-codegen:
#   filename:  commands/auth/login-with-password.json

from __future__ import annotations

from uuid import UUID

from pydantic import AwareDatetime, BaseModel, ConfigDict, EmailStr, Field

from ...ids import ids


class LoginWithPassword(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    email: EmailStr
    password: str


class SessionSummary(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    sessionId: UUID = Field(..., title="SessionId")
    createdAt: AwareDatetime
    lastSeenAt: AwareDatetime
    expiresAt: AwareDatetime
    currentDevice: bool
    status: ids.SessionStatusValue
    lastStrongAuthAt: AwareDatetime | None = None


class LoginWithPasswordResponse(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    accountId: UUID = Field(..., title="UserId")
    accountStatus: ids.AccountStatusValue
    session: SessionSummary
    recoveryModeRequired: bool
