# generated by datamodel-codegen:
#   filename:  commands/auth/logout.json

from __future__ import annotations

from enum import Enum

from pydantic import BaseModel, ConfigDict, constr


class LogoutStatusValue(Enum):
    LoggedOut = "LoggedOut"
    AlreadyLoggedOut = "AlreadyLoggedOut"


class LogoutResponse(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    messageKey: constr(min_length=1)
    sessionStatus: LogoutStatusValue
