# generated by datamodel-codegen:
#   filename:  commands/auth/reauthenticate.json

from __future__ import annotations

from pydantic import AwareDatetime, BaseModel, ConfigDict, constr


class Reauthenticate(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    password: str


class ReauthenticateResponse(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    messageKey: constr(min_length=1)
    reauthenticatedAt: AwareDatetime
    validUntil: AwareDatetime
    windowSeconds: int
