# generated by datamodel-codegen:
#   filename:  commands/auth/register-with-email.json

from __future__ import annotations

from pydantic import BaseModel, ConfigDict, EmailStr, constr


class RegisterWithEmail(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    email: EmailStr
    password: constr(min_length=12, max_length=128)


class RegisterWithEmailResponse(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    messageKey: constr(min_length=1)
    email: EmailStr
