# generated by datamodel-codegen:
#   filename:  commands/auth/request-account-deletion.json

from __future__ import annotations

from pydantic import AwareDatetime, BaseModel, ConfigDict, constr

from ...ids import ids


class RequestAccountDeletionResponse(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    messageKey: constr(min_length=1)
    accountStatus: ids.AccountStatusValue
    deletionRequestedAt: AwareDatetime
    gracePeriodDaysRemaining: int
    executeAfter: AwareDatetime
