# generated by datamodel-codegen:
#   filename:  commands/auth/request-password-reset.json

from __future__ import annotations

from pydantic import AwareDatetime, BaseModel, ConfigDict, EmailStr, constr


class RequestPasswordReset(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    email: EmailStr


class RequestPasswordResetResponse(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    messageKey: constr(min_length=1)
    nextAllowedAt: AwareDatetime
