# generated by datamodel-codegen:
#   filename:  commands/auth/resend-email-verification.json

from __future__ import annotations

from pydantic import AwareDatetime, BaseModel, ConfigDict, EmailStr, constr


class ResendEmailVerification(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    email: EmailStr


class ResendEmailVerificationResponse(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    messageKey: constr(min_length=1)
    nextAllowedAt: AwareDatetime
