# generated by datamodel-codegen:
#   filename:  commands/auth/reset-password.json

from __future__ import annotations

from pydantic import BaseModel, ConfigDict, constr

from ...ids import ids


class ResetPassword(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    token: str
    newPassword: constr(min_length=12, max_length=128)


class ResetPasswordResponse(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    messageKey: constr(min_length=1)
    accountStatus: ids.AccountStatusValue
