# generated by datamodel-codegen:
#   filename:  commands/auth/verify-email.json

from __future__ import annotations

from pydantic import BaseModel, ConfigDict, constr

from ...ids import ids


class VerifyEmail(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    token: str


class VerifyEmailResponse(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    messageKey: constr(min_length=1)
    accountStatus: ids.AccountStatusValue
