# generated by datamodel-codegen:
#   filename:  queries/public-api/list-public-notifications.json

from __future__ import annotations

from typing import Any
from uuid import UUID

from pydantic import BaseModel, ConfigDict, Field


class Item(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    notificationId: UUID = Field(..., title="UserId")
    kind: str
    payload: dict[str, Any]
    readAt: str | None


class GetPublicNotificationsResponse(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    items: list[Item]
