# generated by datamodel-codegen:
#   filename:  queries/public-api/list-public-resources.json

from __future__ import annotations

from uuid import UUID

from pydantic import BaseModel, ConfigDict, Field


class Item(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    resourceId: UUID = Field(..., title="UserId")
    resourceType: str
    name: str
    updatedAt: str | None


class GetPublicResourcesResponse(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    items: list[Item]
