# generated by datamodel-codegen:
#   filename:  queries/tasks/get-task.json

from __future__ import annotations

from pydantic import BaseModel, ConfigDict

from . import list_tasks


class GetTaskResponse(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    task: list_tasks.TaskSummary
