# generated by datamodel-codegen:
#   filename:  queries/tasks/list-tasks.json

from __future__ import annotations

from enum import Enum
from uuid import UUID

from pydantic import (
    AwareDatetime,
    BaseModel,
    ConfigDict,
    Field,
    confloat,
    conint,
    constr,
)


class State(Enum):
    Created = "Created"
    Queued = "Queued"
    Running = "Running"
    WaitingForUser = "WaitingForUser"
    Retrying = "Retrying"
    Succeeded = "Succeeded"
    PartialSucceeded = "PartialSucceeded"
    Failed = "Failed"
    Cancelled = "Cancelled"


class TaskSummary(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    taskId: UUID = Field(..., title="TaskId")
    taskType: constr(min_length=1)
    state: State
    stage: str | None
    messageCode: str | None
    current: conint(ge=0) | None
    total: conint(ge=0) | None
    percentage: confloat(ge=0.0, le=100.0) | None
    updatedAt: AwareDatetime | None
    retryCount: conint(ge=0)
    retryOfTaskId: UUID | None
    cancelRequestedAt: AwareDatetime | None
    queuedAt: AwareDatetime | None
    startedAt: AwareDatetime | None
    finishedAt: AwareDatetime | None
    failureCode: str | None


class ListTasksResponse(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    tasks: list[TaskSummary]
    limit: conint(ge=1, le=100)
    offset: conint(ge=0)
