# generated by datamodel-codegen:
#   filename:  ids/ids.json

from __future__ import annotations

from enum import Enum
from uuid import UUID

from pydantic import BaseModel, ConfigDict, Field


class NodeRef(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    resourceId: UUID = Field(..., title="ResourceId")
    nodeId: UUID = Field(..., title="NodeId")


class AccountStatusValue(Enum):
    PendingVerification = "PendingVerification"
    Active = "Active"
    Disabled = "Disabled"
    DeletionPending = "DeletionPending"
    Deleted = "Deleted"


class SessionStatusValue(Enum):
    Active = "Active"
    Replaced = "Replaced"
    LoggedOut = "LoggedOut"
    Expired = "Expired"
    Revoked = "Revoked"


class SessionReplacementReason(Enum):
    NewDeviceLogin = "NewDeviceLogin"
    UserLogout = "UserLogout"
    PasswordReset = "PasswordReset"
    AccountDisabled = "AccountDisabled"
    Expired = "Expired"
    SecurityRevoke = "SecurityRevoke"


class IdentityIds(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    userId: UUID | None = Field(None, title="UserId")
    workspaceId: UUID | None = Field(None, title="WorkspaceId")
    projectId: UUID | None = Field(None, title="ProjectId")
    folderId: UUID | None = Field(None, title="FolderId")
    resourceId: UUID | None = Field(None, title="ResourceId")
    nodeId: UUID | None = Field(None, title="NodeId")
    taskId: UUID | None = Field(None, title="TaskId")
    attemptId: UUID | None = Field(None, title="AttemptId")
    commentId: UUID | None = Field(None, title="CommentId")
    threadId: UUID | None = Field(None, title="ThreadId")
    assetId: UUID | None = Field(None, title="AssetId")
    eventId: UUID | None = Field(None, title="EventId")
    requestId: UUID | None = Field(None, title="RequestId")
    operationId: UUID | None = Field(None, title="OperationId")
    sessionId: UUID | None = Field(None, title="SessionId")
    subscriptionId: UUID | None = Field(None, title="SubscriptionId")
    deliveryId: UUID | None = Field(None, title="DeliveryId")
    idempotencyKey: UUID | None = Field(None, title="IdempotencyKey")
    accountStatusValue: AccountStatusValue | None = None
    sessionStatusValue: SessionStatusValue | None = None
    sessionReplacementReason: SessionReplacementReason | None = None
    nodeRef: NodeRef | None = None
