# generated by datamodel-codegen:
#   filename:  queries/history/list-versions.json

from __future__ import annotations

from enum import Enum
from uuid import UUID

from pydantic import BaseModel, ConfigDict, Field


class Kind(Enum):
    Checkpoint = "Checkpoint"
    NamedVersion = "NamedVersion"
    Restore = "Restore"


class Item(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    seq: int
    kind: Kind
    label: str | None
    author: str | None
    occurredAt: str | None


class ListVersionsResponse(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    resourceId: UUID = Field(..., title="UserId")
    items: list[Item]
