# generated by datamodel-codegen:
#   filename:  commands/assets/upload-asset.json

from __future__ import annotations

from uuid import UUID

from pydantic import BaseModel, ConfigDict, Field, conint, constr


class UploadAssetBody(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    file: bytes = Field(
        ..., description="The file bytes sent as the multipart field named file."
    )
    mime: constr(max_length=128) | None = None


class UploadAssetResponse(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    assetId: UUID = Field(..., title="AssetId")
    sha256: constr(pattern=r"^[a-f0-9]{64}$")
    sizeBytes: conint(ge=0)


class UploadAsset(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    resourceId: UUID = Field(..., title="ResourceId")
    file: bytes = Field(
        ..., description="The file bytes sent as the multipart field named file."
    )
    mime: constr(max_length=128) | None = None
