# generated by datamodel-codegen:
#   filename:  commands/notifications/mark-notifications-read.json

from __future__ import annotations

from pydantic import BaseModel, ConfigDict


class MarkNotificationsReadResponse(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    marked: int
