# generated by datamodel-codegen:
#   filename:  commands/notifications/mark-notification-read.json

from __future__ import annotations

from uuid import UUID

from pydantic import BaseModel, ConfigDict


class MarkNotificationReadResponse(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    notificationId: UUID
    readAt: str
