# generated by datamodel-codegen:
#   filename:  errors/error-envelope.json

from __future__ import annotations

from enum import Enum
from typing import Any
from uuid import UUID

from pydantic import BaseModel, ConfigDict, Field, constr


class AuthErrorCategory(Enum):
    Validation = "Validation"
    Authentication = "Authentication"
    Permission = "Permission"
    NotFound = "NotFound"
    Conflict = "Conflict"
    RateLimit = "RateLimit"
    Timeout = "Timeout"
    DependencyFailure = "DependencyFailure"
    Unavailable = "Unavailable"
    Internal = "Internal"


class FieldError(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    field: str = Field(..., title="FieldName")
    code: str = Field(..., title="FieldErrorCode")
    message: str = Field(..., title="FieldMessage")


class ErrorEnvelope(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    category: AuthErrorCategory = Field(..., title="AuthErrorCategory")
    errorCode: constr(pattern=r"^[A-Z0-9_]+$") = Field(..., title="ErrorCode")
    messageKey: constr(min_length=1) = Field(..., title="MessageKey")
    message: str | None = Field(None, title="ErrorMessage")
    requestId: UUID = Field(..., title="RequestId")
    retryable: bool = Field(..., title="Retryable")
    fieldErrors: list[FieldError] | None = Field(None, title="FieldErrors")
    details: dict[str, Any] | None = Field(
        None,
        description="Safe, structured business detail only. Must never contain stack traces, SQL, internal hosts, secrets or provider tokens (doc 28 §31).",
        title="ErrorDetails",
    )
