# generated by datamodel-codegen:
#   filename:  queries/ops/get-ops-metrics.json

from __future__ import annotations

from pydantic import BaseModel, ConfigDict


class GetOpsMetricsResponse(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
