# generated by datamodel-codegen:
#   filename:  client-api.yaml

from __future__ import annotations

from enum import Enum
from typing import Any
from uuid import UUID

from pydantic import AwareDatetime, BaseModel, ConfigDict, EmailStr, Field, constr


class RegisterWithEmail(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    email: EmailStr
    password: constr(min_length=12, max_length=128)


class RegisterWithEmailResponse(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    messageKey: constr(min_length=1)
    email: EmailStr


class AuthErrorCategory(Enum):
    Validation = "Validation"
    Authentication = "Authentication"
    Permission = "Permission"
    NotFound = "NotFound"
    Conflict = "Conflict"
    RateLimit = "RateLimit"
    Timeout = "Timeout"
    DependencyFailure = "DependencyFailure"
    Unavailable = "Unavailable"
    Internal = "Internal"


class FieldError(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    field: str = Field(..., title="FieldName")
    code: str = Field(..., title="FieldErrorCode")
    message: str = Field(..., title="FieldMessage")


class VerifyEmail(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    token: str


class AccountStatusValue(Enum):
    PendingVerification = "PendingVerification"
    Active = "Active"
    Disabled = "Disabled"
    DeletionPending = "DeletionPending"
    Deleted = "Deleted"


class ResendEmailVerification(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    email: EmailStr


class ResendEmailVerificationResponse(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    messageKey: constr(min_length=1)
    nextAllowedAt: AwareDatetime


class LoginWithPassword(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    email: EmailStr
    password: str


class SessionStatusValue(Enum):
    Active = "Active"
    Replaced = "Replaced"
    LoggedOut = "LoggedOut"
    Expired = "Expired"
    Revoked = "Revoked"


class LogoutStatusValue(Enum):
    LoggedOut = "LoggedOut"
    AlreadyLoggedOut = "AlreadyLoggedOut"


class GetCurrentAccountResponse(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    accountId: UUID = Field(..., title="UserId")
    primaryEmail: EmailStr
    accountStatus: AccountStatusValue
    emailVerifiedAt: AwareDatetime | None
    createdAt: AwareDatetime
    canCreateWorkspace: bool
    inAccountRecoveryMode: bool


class GetCurrentSessionResponse(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    sessionId: UUID = Field(..., title="SessionId")
    createdAt: AwareDatetime
    lastSeenAt: AwareDatetime
    expiresAt: AwareDatetime
    currentDevice: bool
    status: SessionStatusValue
    lastStrongAuthAt: AwareDatetime | None = None


class RequestPasswordReset(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    email: EmailStr


class RequestPasswordResetResponse(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    messageKey: constr(min_length=1)
    nextAllowedAt: AwareDatetime


class ResetPassword(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    token: str
    newPassword: constr(min_length=12, max_length=128)


class ResetPasswordResponse(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    messageKey: constr(min_length=1)
    accountStatus: AccountStatusValue


class Reauthenticate(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    password: str


class ReauthenticateResponse(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    messageKey: constr(min_length=1)
    reauthenticatedAt: AwareDatetime
    validUntil: AwareDatetime
    windowSeconds: int


class RequestAccountDeletionResponse(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    messageKey: constr(min_length=1)
    accountStatus: AccountStatusValue
    deletionRequestedAt: AwareDatetime
    gracePeriodDaysRemaining: int
    executeAfter: AwareDatetime


class CancelAccountDeletionResponse(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    messageKey: constr(min_length=1)
    accountStatus: AccountStatusValue
    restoredAt: AwareDatetime


class ErrorEnvelope(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    category: AuthErrorCategory = Field(..., title="AuthErrorCategory")
    errorCode: constr(pattern=r"^[A-Z0-9_]+$") = Field(..., title="ErrorCode")
    messageKey: constr(min_length=1) = Field(..., title="MessageKey")
    message: str | None = Field(None, title="ErrorMessage")
    requestId: UUID = Field(..., title="RequestId")
    retryable: bool = Field(..., title="Retryable")
    fieldErrors: list[FieldError] | None = Field(None, title="FieldErrors")
    details: dict[str, Any] | None = Field(
        None,
        description="Safe, structured business detail only. Must never contain stack traces, SQL, internal hosts, secrets or provider tokens (doc 28 §31).",
    )


class VerifyEmailResponse(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    messageKey: constr(min_length=1)
    accountStatus: AccountStatusValue


class SessionSummary(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    sessionId: UUID = Field(..., title="SessionId")
    createdAt: AwareDatetime
    lastSeenAt: AwareDatetime
    expiresAt: AwareDatetime
    currentDevice: bool
    status: SessionStatusValue
    lastStrongAuthAt: AwareDatetime | None = None


class LogoutResponse(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    messageKey: constr(min_length=1)
    sessionStatus: LogoutStatusValue


class LoginWithPasswordResponse(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    accountId: UUID = Field(..., title="UserId")
    accountStatus: AccountStatusValue
    session: SessionSummary
    recoveryModeRequired: bool
