# generated by datamodel-codegen:
#   filename:  realtime/awareness-participant.json

from __future__ import annotations

from pydantic import BaseModel, ConfigDict, constr


class AwarenessParticipant(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    participantId: constr(min_length=1)
    displayName: constr(min_length=1)
    color: constr(pattern=r"^#[0-9a-fA-F]{6}$")
