# generated by datamodel-codegen:
#   filename:  realtime/awareness-state.json

from __future__ import annotations

from pydantic import BaseModel, ConfigDict, conint


class CursorSelection(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    anchor: conint(ge=0, le=10000000)
    head: conint(ge=0, le=10000000)


class AwarenessState(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    cursor: CursorSelection | None
