# generated by datamodel-codegen:
#   filename:  realtime/awareness-event.json

from __future__ import annotations

from typing import Literal

from pydantic import BaseModel, ConfigDict, Field, RootModel, constr

from . import awareness_participant, awareness_state


class AwarenessRemove(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    kind: Literal["remove"]
    participantId: constr(min_length=1)


class AwarenessUpdate(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    kind: Literal["update"]
    participant: awareness_participant.AwarenessParticipant
    state: awareness_state.AwarenessState


class AwarenessEvent(RootModel[AwarenessUpdate | AwarenessRemove]):
    root: AwarenessUpdate | AwarenessRemove = Field(
        ...,
        description="Ephemeral, lossy Resource Awareness update or participant removal. It is not persisted as document content.",
        title="AwarenessEvent",
    )
