# generated by datamodel-codegen:
#   filename:  realtime/comment-event.json

from __future__ import annotations

from enum import Enum
from typing import Literal
from uuid import UUID

from pydantic import (
    AwareDatetime,
    BaseModel,
    ConfigDict,
    Field,
    RootModel,
    conint,
    constr,
)


class Status(Enum):
    Open = "Open"
    Resolved = "Resolved"


class CommentAddedPayload(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    resourceId: UUID = Field(..., title="ResourceId")
    commentId: UUID = Field(..., title="CommentId")
    threadId: UUID = Field(..., title="ThreadId")
    author: UUID = Field(..., title="UserId")
    body: constr(min_length=1)


class CommentEditedPayload(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    commentId: UUID = Field(..., title="CommentId")
    body: constr(min_length=1)


class CommentDeletedPayload(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    commentId: UUID = Field(..., title="CommentId")


class ThreadTransitionPayload(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    threadId: UUID = Field(..., title="ThreadId")
    resourceId: UUID = Field(..., title="ResourceId")
    status: Status
    resolvedBy: UUID | None
    resolvedAt: AwareDatetime | None


class CommentAddedFrame(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    protocolVersion: Literal[1]
    subject: constr(pattern=r"^rt\.resource\.[0-9a-fA-F-]{36}$")
    resourceId: UUID = Field(..., title="ResourceId")
    subscriptionId: UUID = Field(..., title="SubscriptionId")
    kind: Literal["comment.added"]
    payload: CommentAddedPayload
    sequence: conint(ge=0) | None = None
    occurredAt: AwareDatetime


class CommentEditedFrame(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    protocolVersion: Literal[1]
    subject: constr(pattern=r"^rt\.resource\.[0-9a-fA-F-]{36}$")
    resourceId: UUID = Field(..., title="ResourceId")
    subscriptionId: UUID = Field(..., title="SubscriptionId")
    kind: Literal["comment.edited"]
    payload: CommentEditedPayload
    sequence: conint(ge=0) | None = None
    occurredAt: AwareDatetime


class CommentDeletedFrame(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    protocolVersion: Literal[1]
    subject: constr(pattern=r"^rt\.resource\.[0-9a-fA-F-]{36}$")
    resourceId: UUID = Field(..., title="ResourceId")
    subscriptionId: UUID = Field(..., title="SubscriptionId")
    kind: Literal["comment.deleted"]
    payload: CommentDeletedPayload
    sequence: conint(ge=0) | None = None
    occurredAt: AwareDatetime


class ThreadResolvedPayload(ThreadTransitionPayload):
    status: Literal["Resolved"]


class ThreadReopenedPayload(ThreadTransitionPayload):
    status: Literal["Open"]


class ThreadResolvedFrame(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    protocolVersion: Literal[1]
    subject: constr(pattern=r"^rt\.resource\.[0-9a-fA-F-]{36}$")
    resourceId: UUID = Field(..., title="ResourceId")
    subscriptionId: UUID = Field(..., title="SubscriptionId")
    kind: Literal["ThreadResolved"]
    payload: ThreadResolvedPayload
    sequence: conint(ge=0) | None = None
    occurredAt: AwareDatetime


class ThreadReopenedFrame(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    protocolVersion: Literal[1]
    subject: constr(pattern=r"^rt\.resource\.[0-9a-fA-F-]{36}$")
    resourceId: UUID = Field(..., title="ResourceId")
    subscriptionId: UUID = Field(..., title="SubscriptionId")
    kind: Literal["ThreadReopened"]
    payload: ThreadReopenedPayload
    sequence: conint(ge=0) | None = None
    occurredAt: AwareDatetime


class CommentRealtimeEvent(
    RootModel[
        CommentAddedFrame
        | CommentEditedFrame
        | CommentDeletedFrame
        | ThreadResolvedFrame
        | ThreadReopenedFrame
    ]
):
    root: (
        CommentAddedFrame
        | CommentEditedFrame
        | CommentDeletedFrame
        | ThreadResolvedFrame
        | ThreadReopenedFrame
    ) = Field(
        ...,
        description="A Resource-scoped comment event delivered on the authenticated Realtime subscription.",
        title="CommentRealtimeEvent",
    )
