# generated by datamodel-codegen:
#   filename:  realtime/control-frame.json

from __future__ import annotations

from typing import Any

from pydantic import BaseModel, ConfigDict, Field

from . import frame_header


class RealtimeControlFrame(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    header: frame_header.RealtimeControlFrameHeader
    payload: dict[str, Any] = Field(
        ...,
        description="Operation-specific Control payload; its fields are validated by the corresponding operation contract.",
    )
