# generated by datamodel-codegen:
#   filename:  realtime/frame-header.json

from __future__ import annotations

from enum import Enum
from typing import Literal
from uuid import UUID

from pydantic import BaseModel, ConfigDict, Field, RootModel, conint, constr


class FrameType(Enum):
    Control = "Control"
    Sync = "Sync"
    Awareness = "Awareness"
    System = "System"


class PayloadKind(Enum):
    binary = "binary"
    json = "json"


class RealtimeControlMessageType(Enum):
    connect = "connect"
    ready = "ready"
    subscribe = "subscribe"
    subscribed = "subscribed"
    unsubscribe = "unsubscribe"
    permission = "permission"
    schema = "schema"
    error = "error"
    ping = "ping"
    pong = "pong"


class RealtimeSyncMessageType(Enum):
    sync_update = "sync.update"
    sync_state_vector = "sync.state-vector"


class RealtimeFrameHeaderBase(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    protocolVersion: Literal[1]
    frameType: FrameType
    messageType: constr(min_length=1)
    payloadKind: PayloadKind
    resourceId: UUID | None = Field(None, title="ResourceId")
    subscriptionId: UUID | None = Field(None, title="SubscriptionId")
    requestId: UUID | None = Field(None, title="RequestId")
    acceptedWatermark: conint(ge=0) | None = None
    durableWatermark: conint(ge=0) | None = None


class RealtimeControlFrameHeader(RealtimeFrameHeaderBase):
    frameType: Literal["Control"]
    payloadKind: Literal["json"]
    messageType: RealtimeControlMessageType = Field(
        ..., title="RealtimeControlMessageType"
    )


class RealtimeSyncFrameHeader(RealtimeFrameHeaderBase):
    frameType: Literal["Sync"]
    payloadKind: Literal["binary"]
    messageType: RealtimeSyncMessageType = Field(..., title="RealtimeSyncMessageType")
    resourceId: UUID = Field(..., title="ResourceId")
    subscriptionId: UUID = Field(..., title="SubscriptionId")


class RealtimeAwarenessFrameHeader(RealtimeFrameHeaderBase):
    frameType: Literal["Awareness"]
    payloadKind: Literal["binary"]
    resourceId: UUID = Field(..., title="ResourceId")
    subscriptionId: UUID = Field(..., title="SubscriptionId")
    messageType: constr(min_length=1)


class RealtimeSystemFrameHeader(RealtimeFrameHeaderBase):
    frameType: Literal["System"]
    payloadKind: Literal["json"]
    messageType: constr(min_length=1)


class RealtimeFrameHeader(
    RootModel[
        RealtimeControlFrameHeader
        | RealtimeSyncFrameHeader
        | RealtimeAwarenessFrameHeader
        | RealtimeSystemFrameHeader
    ]
):
    root: (
        RealtimeControlFrameHeader
        | RealtimeSyncFrameHeader
        | RealtimeAwarenessFrameHeader
        | RealtimeSystemFrameHeader
    ) = Field(
        ...,
        description="Common WebSocket frame routing header. Resource and subscription identity are required for Resource-scoped Sync and Awareness frames.",
        title="RealtimeFrameHeader",
    )
