# generated by datamodel-codegen:
#   filename:  realtime/public-share-frame.json

from __future__ import annotations

from enum import Enum
from typing import Literal
from uuid import UUID

from pydantic import BaseModel, ConfigDict, Field, RootModel, constr


class AuthenticateShareFrame(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    protocolVersion: Literal[1]
    type: Literal["authenticate-share"]
    token: constr(min_length=24, max_length=512)


class ShareAuthenticatedPayload(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    status: Literal["ok"]


class ShareAuthenticatedFrame(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    protocolVersion: Literal[1]
    type: Literal["share-authenticated"]
    payload: ShareAuthenticatedPayload = Field(..., title="ShareAuthenticatedPayload")


class StateKind(Enum):
    yjs = "yjs"
    checkpoint = "checkpoint"


class ShareStatePayload(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    stateKind: StateKind


class ShareStateFrame(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    protocolVersion: Literal[1]
    type: Literal["share-state"]
    resourceId: UUID = Field(..., title="ResourceId")
    subscriptionId: UUID = Field(..., title="SubscriptionId")
    payload: ShareStatePayload = Field(..., title="ShareStatePayload")


class PublicShareRealtimeFrame(
    RootModel[AuthenticateShareFrame | ShareAuthenticatedFrame | ShareStateFrame]
):
    root: AuthenticateShareFrame | ShareAuthenticatedFrame | ShareStateFrame = Field(
        ...,
        description="Token-authenticated read-only Resource subscription for an active public share link.",
        title="PublicShareRealtimeFrame",
    )
