# generated by datamodel-codegen:
#   filename:  realtime/system-frame.json

from __future__ import annotations

from typing import Any

from pydantic import BaseModel, ConfigDict, Field

from . import frame_header


class RealtimeSystemFrame(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    header: frame_header.RealtimeSystemFrameHeader
    payload: dict[str, Any] = Field(
        ...,
        description="System message-specific fields; exact fields are owned by each system message definition.",
    )
