# generated by datamodel-codegen:
#   filename:  queries/resource/list-resources.json

from __future__ import annotations

from enum import Enum
from uuid import UUID

from pydantic import BaseModel, ConfigDict, Field


class ResourceType(Enum):
    document = "document"
    code = "code"
    markdown = "markdown"
    text = "text"


class Lifecycle(Enum):
    Active = "Active"
    Trashed = "Trashed"
    Purging = "Purging"
    Purged = "Purged"


class Item(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    resourceId: UUID = Field(..., title="UserId")
    folderId: UUID | None = None
    name: str
    resourceType: ResourceType
    lifecycle: Lifecycle


class ListResourcesResponse(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    projectId: UUID = Field(..., title="WorkspaceId")
    items: list[Item]
