# generated by datamodel-codegen:
#   filename:  queries/resource/open-resource.json

from __future__ import annotations

from enum import Enum
from typing import Any
from uuid import UUID

from pydantic import BaseModel, ConfigDict, Field


class ResourceType(Enum):
    document = "document"
    code = "code"
    markdown = "markdown"
    text = "text"


class Lifecycle(Enum):
    Active = "Active"
    Trashed = "Trashed"
    Purging = "Purging"
    Purged = "Purged"


class OpenResourceResponse(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    resourceId: UUID = Field(..., title="UserId")
    projectId: UUID = Field(..., title="WorkspaceId")
    folderId: UUID | None
    resourceType: ResourceType
    name: str
    lifecycle: Lifecycle
    journalSeq: int
    snapshot: dict[str, Any] | None
