# generated by datamodel-codegen:
#   filename:  queries/resource/read-resource-content.json

from __future__ import annotations

from uuid import UUID

from pydantic import BaseModel, ConfigDict, Field, conint

from . import open_resource


class ReadResourceContent(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    resourceId: UUID = Field(..., title="ResourceId")
    atJournalSeq: conint(ge=0) | None = None


class ReadResourceContentResponse(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    resourceId: UUID = Field(..., title="ResourceId")
    journalSeq: conint(ge=0)
    snapshot: open_resource.ContentSnapshot
