# generated by datamodel-codegen:
#   filename:  commands/ai/apply-changeset.json

from __future__ import annotations

from enum import Enum
from uuid import UUID

from pydantic import BaseModel, ConfigDict, Field, conint


class Status(Enum):
    Applied = "Applied"


class ApplyChangeSetResponse(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    changesetId: UUID = Field(..., title="ChangeSetId")
    journalSeq: conint(ge=1)
    status: Status
