# generated by datamodel-codegen:
#   filename:  commands/ai/propose-changeset.json

from __future__ import annotations

from enum import Enum
from typing import Any
from uuid import UUID

from pydantic import BaseModel, ConfigDict, Field, constr


class ProposeChangeSet(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    resourceId: UUID = Field(..., title="ResourceId")
    instruction: constr(min_length=1, max_length=4000)


class Status(Enum):
    Proposed = "Proposed"


class ProposeChangeSetResponse(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    changesetId: UUID = Field(..., title="ChangeSetId")
    resourceId: UUID = Field(..., title="ResourceId")
    instruction: str
    operations: list[dict[str, Any]]
    status: Status
