# generated by datamodel-codegen:
#   filename:  commands/webhook/register-webhook.json

from __future__ import annotations

from uuid import UUID

from pydantic import BaseModel, ConfigDict, Field, constr


class RegisterWebhook(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    url: constr(max_length=2000)


class RegisterWebhookResponse(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    subscriptionId: UUID = Field(..., title="UserId")
