# generated by datamodel-codegen:
#   filename:  commands/webhook/remove-webhook.json

from __future__ import annotations

from pydantic import BaseModel, ConfigDict


class RemoveWebhookResponse(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    removed: bool
