# generated by datamodel-codegen:
#   filename:  commands/webhook/test-webhook.json

from __future__ import annotations

from pydantic import BaseModel, ConfigDict


class TestWebhookResponse(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    delivered: bool
    statusCode: int
