# generated by datamodel-codegen:
#   filename:  queries/assets/download-asset.json

from __future__ import annotations

from pydantic import Field, RootModel


class DownloadAssetResponse(RootModel[str]):
    root: str = Field(
        ...,
        description="Raw bytes for an authenticated Resource Asset download. Asset metadata is conveyed through response headers; binary content is not Base64-encoded JSON.",
        json_schema_extra={"contentMediaType": "application/octet-stream"},
        title="DownloadAssetResponse",
    )
