# generated by datamodel-codegen:
#   filename:  queries/assets/download-public-shared-asset.json

from __future__ import annotations

from pydantic import Field, RootModel


class DownloadPublicSharedAssetResponse(RootModel[str]):
    root: str = Field(
        ...,
        description="Raw bytes for an asset referenced by a Resource under an active public share link.",
        json_schema_extra={"contentMediaType": "application/octet-stream"},
        title="DownloadPublicSharedAssetResponse",
    )
