# generated by datamodel-codegen:
#   filename:  queries/assets/list-resource-assets.json

from __future__ import annotations

from uuid import UUID

from pydantic import AwareDatetime, BaseModel, ConfigDict, Field, conint, constr


class Asset(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    assetId: UUID = Field(..., title="AssetId")
    originalName: constr(min_length=1, max_length=255)
    mime: constr(max_length=128) | None
    sizeBytes: conint(ge=0)
    sha256: constr(pattern=r"^[a-f0-9]{64}$")
    createdAt: AwareDatetime


class ListResourceAssetsResponse(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    resourceId: UUID = Field(..., title="ResourceId")
    assets: list[Asset]
