# generated by datamodel-codegen:
#   filename:  commands/workspace/archive-project.json

from __future__ import annotations

from typing import Literal
from uuid import UUID

from pydantic import AwareDatetime, BaseModel, ConfigDict, Field


class ArchiveProject(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    projectId: UUID = Field(..., title="ProjectId")
    idempotencyKey: UUID = Field(..., title="IdempotencyKey")


class ArchiveProjectResponse(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    projectId: UUID = Field(..., title="ProjectId")
    lifecycle: Literal["Archived"]
    updatedAt: AwareDatetime
