# generated by datamodel-codegen:
#   filename:  commands/workspace/create-project.json

from __future__ import annotations

from uuid import UUID

from pydantic import AwareDatetime, BaseModel, ConfigDict, Field, constr


class CreateProject(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    workspaceId: UUID = Field(..., title="WorkspaceId")
    name: constr(min_length=1, max_length=120)
    idempotencyKey: UUID = Field(..., title="IdempotencyKey")


class CreateProjectResponse(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    projectId: UUID = Field(..., title="ProjectId")
    workspaceId: UUID = Field(..., title="WorkspaceId")
    name: str
    createdAt: AwareDatetime
