# generated by datamodel-codegen:
#   filename:  commands/workspace/create-workspace.json

from __future__ import annotations

from uuid import UUID

from pydantic import AwareDatetime, BaseModel, ConfigDict, Field, constr


class CreateWorkspace(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    name: constr(min_length=1, max_length=120)
    idempotencyKey: UUID = Field(..., title="IdempotencyKey")


class CreateWorkspaceResponse(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    workspaceId: UUID = Field(..., title="WorkspaceId")
    name: str
    ownerAccountId: UUID = Field(..., title="UserId")
    createdAt: AwareDatetime
