# generated by datamodel-codegen:
#   filename:  commands/workspace/move-folder.json

from __future__ import annotations

from uuid import UUID

from pydantic import AwareDatetime, BaseModel, ConfigDict, Field


class MoveFolder(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    folderId: UUID = Field(..., title="FolderId")
    destinationParentFolderId: UUID | None
    idempotencyKey: UUID = Field(..., title="IdempotencyKey")


class MoveFolderResponse(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    folderId: UUID = Field(..., title="FolderId")
    projectId: UUID = Field(..., title="ProjectId")
    parentFolderId: UUID | None
    updatedAt: AwareDatetime
