# generated by datamodel-codegen:
#   filename:  commands/workspace/rename-folder.json

from __future__ import annotations

from uuid import UUID

from pydantic import AwareDatetime, BaseModel, ConfigDict, Field, constr


class RenameFolder(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    folderId: UUID = Field(..., title="FolderId")
    name: constr(min_length=1, max_length=120)
    idempotencyKey: UUID = Field(..., title="IdempotencyKey")


class RenameFolderResponse(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    folderId: UUID = Field(..., title="FolderId")
    projectId: UUID = Field(..., title="ProjectId")
    parentFolderId: UUID | None
    name: str
    updatedAt: AwareDatetime
