# generated by datamodel-codegen:
#   filename:  commands/workspace/rename-project.json

from __future__ import annotations

from uuid import UUID

from pydantic import AwareDatetime, BaseModel, ConfigDict, Field, constr


class RenameProject(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    projectId: UUID = Field(..., title="ProjectId")
    name: constr(min_length=1, max_length=120)
    idempotencyKey: UUID = Field(..., title="IdempotencyKey")


class RenameProjectResponse(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    projectId: UUID = Field(..., title="ProjectId")
    name: str
    updatedAt: AwareDatetime
