# generated by datamodel-codegen:
#   filename:  commands/workspace/restore-project.json

from __future__ import annotations

from typing import Literal
from uuid import UUID

from pydantic import AwareDatetime, BaseModel, ConfigDict, Field, conint


class RestoreProject(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    projectId: UUID = Field(..., title="ProjectId")
    idempotencyKey: UUID = Field(..., title="IdempotencyKey")


class RestoreProjectResponse(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    projectId: UUID = Field(..., title="ProjectId")
    lifecycle: Literal["Active"]
    restoredDescendantCount: conint(ge=0)
    restoredAt: AwareDatetime
