# generated by datamodel-codegen:
#   filename:  commands/workspace/restore-folder.json

from __future__ import annotations

from typing import Literal
from uuid import UUID

from pydantic import AwareDatetime, BaseModel, ConfigDict, Field, conint


class RestoreFolder(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    folderId: UUID = Field(..., title="FolderId")
    idempotencyKey: UUID = Field(..., title="IdempotencyKey")


class RestoreFolderResponse(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    folderId: UUID = Field(..., title="FolderId")
    projectId: UUID = Field(..., title="ProjectId")
    parentFolderId: UUID | None
    name: str
    lifecycle: Literal["Active"]
    restoredDescendantCount: conint(ge=0)
    restoredAt: AwareDatetime
