# generated by datamodel-codegen:
#   filename:  commands/workspace/trash-project.json

from __future__ import annotations

from typing import Literal
from uuid import UUID

from pydantic import AwareDatetime, BaseModel, ConfigDict, Field


class TrashProject(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    projectId: UUID = Field(..., title="ProjectId")
    idempotencyKey: UUID = Field(..., title="IdempotencyKey")


class TrashProjectResponse(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    projectId: UUID = Field(..., title="ProjectId")
    lifecycle: Literal["Trashed"]
    effectiveDescendantLifecycle: Literal["Trashed"]
    trashedAt: AwareDatetime
    purgeEligibleAt: AwareDatetime
