# generated by datamodel-codegen:
#   filename:  commands/workspace/trash-folder.json

from __future__ import annotations

from typing import Literal
from uuid import UUID

from pydantic import AwareDatetime, BaseModel, ConfigDict, Field


class TrashFolder(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    folderId: UUID = Field(..., title="FolderId")
    idempotencyKey: UUID = Field(..., title="IdempotencyKey")


class TrashFolderResponse(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    folderId: UUID = Field(..., title="FolderId")
    lifecycle: Literal["Trashed"]
    effectiveDescendantLifecycle: Literal["Trashed"]
    trashedAt: AwareDatetime
    purgeEligibleAt: AwareDatetime
