# generated by datamodel-codegen:
#   filename:  commands/workspace/unarchive-project.json

from __future__ import annotations

from typing import Literal
from uuid import UUID

from pydantic import AwareDatetime, BaseModel, ConfigDict, Field


class UnarchiveProject(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    projectId: UUID = Field(..., title="ProjectId")
    idempotencyKey: UUID = Field(..., title="IdempotencyKey")


class UnarchiveProjectResponse(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    projectId: UUID = Field(..., title="ProjectId")
    lifecycle: Literal["Active"]
    updatedAt: AwareDatetime
