"""Drift gate for the generated ``app_contracts.models`` artifact (doc 27 §53).

This test makes the contract drift check a standing gate rather than a habit:

1. ``scripts/generate_contracts.py --check`` exits 0 (no drift vs committed artifact).
2. Idempotence / determinism: two independent generations are byte-identical.
3. ``--check`` is non-mutating: the committed file's hash is unchanged after a check.
4. The generated module imports and its key symbols match the canonical contracts.
5. No hand-editing / no name collisions: generator header present, no ``Foo1`` classes.
6. False-green guard: the comparison logic actually reports real drift.

Repo root is resolved via ``Path(__file__).resolve().parents[2]`` (not cwd), because
the generator and the artifact live at fixed locations inside the monorepo.
"""

from __future__ import annotations

import hashlib
import importlib.util
import subprocess
import sys
import tempfile
from pathlib import Path
from shutil import copyfile

REPO_ROOT = Path(__file__).resolve().parents[2]
GEN_SCRIPT = REPO_ROOT / "scripts" / "generate_contracts.py"
COMMITTED = (
    REPO_ROOT / "packages" / "py" / "contracts" / "src" / "app_contracts" / "models.py"
)

# doc 28 §... canonical PRD account states and the ten error categories from
# doc 04 §23 / Constitution §3.19.
PRD_ACCOUNT_STATES = frozenset(
    {"PendingVerification", "Active", "Disabled", "DeletionPending", "Deleted"}
)
CANONICAL_ERROR_CATEGORIES = frozenset(
    {
        "Validation",
        "Authentication",
        "Permission",
        "NotFound",
        "Conflict",
        "RateLimit",
        "Timeout",
        "DependencyFailure",
        "Unavailable",
        "Internal",
    }
)


def _load_gen_module():
    """Import the generator script as a module (only called inside tests)."""
    if not GEN_SCRIPT.exists():
        raise FileNotFoundError(f"generator script missing: {GEN_SCRIPT}")
    spec = importlib.util.spec_from_file_location("gen_contracts", GEN_SCRIPT)
    if spec is None or spec.loader is None:
        raise ImportError(f"cannot load generator module from {GEN_SCRIPT}")
    module = importlib.util.module_from_spec(spec)
    sys.modules[spec.name] = module
    spec.loader.exec_module(module)
    return module


def _sha256(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def test_drift_check_exits_zero():
    """DELIVERABLE 3.1 — ``--check`` passes against the committed artifact."""
    result = subprocess.run(
        [sys.executable, str(GEN_SCRIPT), "--check"],
        capture_output=True,
        text=True,
    )
    assert result.returncode == 0, (
        f"--check exited {result.returncode}\n"
        f"STDOUT:\n{result.stdout}\nSTDERR:\n{result.stderr}"
    )


def test_generation_is_idempotent():
    """DELIVERABLE 3.2 — two independent generations are byte-identical."""
    gen = _load_gen_module()
    with tempfile.TemporaryDirectory() as td:
        a = Path(td) / "a" / "models.py"
        b = Path(td) / "b" / "models.py"
        gen.run_codegen(a)
        gen.format_file(a)
        gen.run_codegen(b)
        gen.format_file(b)
        assert a.read_bytes() == b.read_bytes(), (
            "two generations are not byte-identical"
        )


def test_check_is_non_mutating():
    """DELIVERABLE 3.3 — ``--check`` leaves the committed file untouched."""
    before = _sha256(COMMITTED)
    result = subprocess.run(
        [sys.executable, str(GEN_SCRIPT), "--check"],
        capture_output=True,
        text=True,
    )
    after = _sha256(COMMITTED)
    assert result.returncode == 0
    assert before == after, "committed models.py hash changed after --check (mutating!)"


def test_generated_symbols_match_contracts():
    """DELIVERABLE 3.4 — imports and key symbols match canonical contracts."""
    import app_contracts.models as m

    assert hasattr(m, "ErrorEnvelope"), "ErrorEnvelope missing"
    assert hasattr(m, "RegisterWithEmailResponse"), "RegisterWithEmailResponse missing"

    status = m.AccountStatusValue
    assert {e.value for e in status} == PRD_ACCOUNT_STATES, (
        f"AccountStatusValue mismatch: {[e.value for e in status]}"
    )

    category = m.AuthErrorCategory
    assert {e.value for e in category} == CANONICAL_ERROR_CATEGORIES, (
        f"AuthErrorCategory mismatch: {[e.value for e in category]}"
    )


def test_no_hand_editing_no_name_collisions():
    """DELIVERABLE 3.5 — generator header present; no ``Foo1``-style classes."""
    assert COMMITTED.exists(), f"committed artifact missing: {COMMITTED}"
    text = COMMITTED.read_text(encoding="utf-8")
    assert text.startswith("# generated by datamodel-codegen:"), (
        "generator header missing (file may be hand-edited)"
    )

    import re

    class_lines = re.findall(r"^class\s+(\w+)", text, flags=re.MULTILINE)
    assert class_lines, "no classes found"
    digit_suffixed = [c for c in class_lines if c[-1].isdigit()]
    assert not digit_suffixed, f"name-collision classes found: {digit_suffixed}"


def test_false_green_guard():
    """DELIVERABLE 3.6 — the comparison logic actually reports real drift."""
    gen = _load_gen_module()
    assert gen.compare_generated(COMMITTED, COMMITTED) == [], (
        "compare_generated must report no drift for identical inputs"
    )

    with tempfile.TemporaryDirectory() as td:
        corrupted = Path(td) / "models.py"
        copyfile(COMMITTED, corrupted)
        text = corrupted.read_text(encoding="utf-8")
        # byte-perturb a class name so the artifact is no longer identical
        perturbed = text.replace(
            "class RegisterWithEmailResponse",
            "class RegisterWithEmailResponseCorrupt",
            1,
        )
        assert perturbed != text, "perturbation did not change the source text"
        corrupted.write_text(perturbed, encoding="utf-8")

        drift = gen.compare_generated(COMMITTED, corrupted)
        assert drift, "compare_generated failed to detect real drift (false green!)"
