from __future__ import annotations

from typing import Protocol
from uuid import UUID

from app_core.comments.domain import Comment


class CommentsRepository(Protocol):
    async def save(self, comment: Comment) -> Comment: ...
    async def list_by_resource(self, resource_id: UUID) -> list[Comment]: ...
    async def find_by_id(self, comment_id: UUID) -> Comment | None: ...
    async def update_body(self, comment_id: UUID, body: str) -> None: ...
    async def mark_deleted(self, comment_id: UUID) -> None: ...
