# generated by datamodel-codegen:
#   filename:  commands/integrations/rotate-api-key.json

from __future__ import annotations

from uuid import UUID

from pydantic import BaseModel, ConfigDict, Field


class RotateApiKey(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    label: str


class RotateApiKeyResponse(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    keyId: UUID = Field(..., title="UserId")
    revokedKeyId: UUID = Field(..., title="UserId")
    label: str
    privateKeyHex: str
