# generated by datamodel-codegen:
#   filename:  commands/search/clear-search-history.json

from __future__ import annotations

from pydantic import BaseModel, ConfigDict


class ClearSearchHistoryResponse(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    cleared: int
