# generated by datamodel-codegen:
#   filename:  queries/importexport/export-resource.json

from __future__ import annotations

from enum import Enum
from typing import Any, Literal
from uuid import UUID

from pydantic import AwareDatetime, BaseModel, ConfigDict, Field


class ResourceType(Enum):
    document = "document"
    code = "code"
    markdown = "markdown"
    text = "text"


class Content(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    snapshot: dict[str, Any] | None
    journalSeq: int


class Resource(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    resourceId: UUID = Field(..., title="ResourceId")
    resourceType: ResourceType
    name: str


class ExportResourceResponse(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    kind: Literal["dom.resource.export.v1"]
    schemaVersion: Literal["1.0.0"]
    exportedAt: AwareDatetime
    resource: Resource
    content: Content
