# generated by datamodel-codegen:
#   filename:  events/auth/session-replaced.json

from __future__ import annotations

from typing import Literal
from uuid import UUID

from pydantic import AwareDatetime, BaseModel, ConfigDict, Field, constr

from ...ids import ids


class SessionReplacedPayload(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    userId: UUID = Field(..., title="UserId")
    replacedSessionId: UUID = Field(..., title="SessionId")
    replacedBySessionId: UUID = Field(..., title="SessionId")
    invalidationReason: ids.SessionReplacementReason
    replacedAt: AwareDatetime


class SessionReplaced(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    eventId: UUID = Field(..., title="EventId")
    eventType: Literal["SessionReplaced"]
    schemaVersion: constr(pattern=r"^\d+\.\d+\.\d+$")
    occurredAt: AwareDatetime
    producer: str
    traceId: str | None = None
    actorRef: UUID | None = Field(None, title="UserId")
    workspaceId: UUID | None = Field(None, title="WorkspaceId")
    resourceId: UUID | None = Field(None, title="ResourceId")
    payload: SessionReplacedPayload
