# generated by datamodel-codegen:
#   filename:  commands/permission/accept-workspace-invitation-by-id.json

from __future__ import annotations

from enum import Enum
from uuid import UUID

from pydantic import AwareDatetime, BaseModel, ConfigDict, Field


class MembershipKind(Enum):
    Owner = "Owner"
    Member = "Member"


class AcceptWorkspaceInvitationByIdResponse(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    workspaceId: UUID = Field(..., title="WorkspaceId")
    accountId: UUID = Field(..., title="UserId")
    membershipKind: MembershipKind
    email: str
    createdAt: AwareDatetime
