# generated by datamodel-codegen:
#   filename:  commands/permission/accept-workspace-invitation.json

from __future__ import annotations

from enum import Enum
from uuid import UUID

from pydantic import AwareDatetime, BaseModel, ConfigDict, Field, constr


class AcceptWorkspaceInvitation(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    token: constr(min_length=32, max_length=256)


class MembershipKind(Enum):
    Owner = "Owner"
    Member = "Member"


class AcceptWorkspaceInvitationResponse(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    workspaceId: UUID = Field(..., title="WorkspaceId")
    accountId: UUID = Field(..., title="UserId")
    membershipKind: MembershipKind
    email: str
    createdAt: AwareDatetime
