# generated by datamodel-codegen:
#   filename:  commands/permission/create-workspace-invitation.json

from __future__ import annotations

from typing import Literal
from uuid import UUID

from pydantic import (
    AwareDatetime,
    BaseModel,
    ConfigDict,
    EmailStr,
    Field,
    conint,
    constr,
)


class CreateWorkspaceInvitation(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    workspaceId: UUID = Field(..., title="WorkspaceId")
    targetEmail: EmailStr
    expiresInDays: conint(ge=1, le=30) | None = 7


class CreateWorkspaceInvitationResponse(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    invitationId: UUID = Field(..., title="InvitationId")
    workspaceId: UUID = Field(..., title="WorkspaceId")
    targetEmail: EmailStr
    role: Literal["Member"]
    state: Literal["Pending"]
    expiresAt: AwareDatetime
    createdBy: UUID = Field(..., title="UserId")
    createdAt: AwareDatetime
    invitationUrl: constr(min_length=1)
    notificationSent: bool | None = None
