# generated by datamodel-codegen:
#   filename:  commands/permission/create-resource-share-link.json

from __future__ import annotations

from pydantic import AwareDatetime, BaseModel, ConfigDict, constr

from ...queries.permission import list_resource_share_links


class CreateResourceShareLink(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    expiresAt: AwareDatetime | None


class CreateResourceShareLinkResponse(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    shareLink: list_resource_share_links.ShareLinkMetadata
    shareUrl: constr(min_length=1)
