# generated by datamodel-codegen:
#   filename:  commands/permission/remove-resource-permission.json

from __future__ import annotations

from typing import Literal
from uuid import UUID

from pydantic import BaseModel, ConfigDict, Field


class RemoveResourcePermission(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    resourceId: UUID = Field(..., title="ResourceId")
    accountId: UUID = Field(..., title="UserId")


class RemoveResourcePermissionResponse(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    removed: Literal[True]
    resourceId: UUID = Field(..., title="ResourceId")
    accountId: UUID = Field(..., title="UserId")
