# generated by datamodel-codegen:
#   filename:  commands/permission/remove-workspace-member.json

from __future__ import annotations

from typing import Literal
from uuid import UUID

from pydantic import BaseModel, ConfigDict, Field


class RemoveWorkspaceMember(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    workspaceId: UUID = Field(..., title="WorkspaceId")
    accountId: UUID = Field(..., title="UserId")


class RemoveWorkspaceMemberResponse(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    removed: Literal[True]
    workspaceId: UUID = Field(..., title="WorkspaceId")
    accountId: UUID = Field(..., title="UserId")
