# generated by datamodel-codegen:
#   filename:  commands/permission/remove-project-member.json

from __future__ import annotations

from typing import Literal
from uuid import UUID

from pydantic import BaseModel, ConfigDict, Field


class RemoveProjectMember(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    projectId: UUID = Field(..., title="ProjectId")
    accountId: UUID = Field(..., title="UserId")


class RemoveProjectMemberResponse(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    removed: Literal[True]
    projectId: UUID = Field(..., title="ProjectId")
    accountId: UUID = Field(..., title="UserId")
