# generated by datamodel-codegen:
#   filename:  commands/permission/revoke-resource-share-link.json

from __future__ import annotations

from pydantic import BaseModel, ConfigDict

from ...queries.permission import list_resource_share_links


class RevokeResourceShareLinkResponse(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    shareLink: list_resource_share_links.ShareLinkMetadata
