# generated by datamodel-codegen:
#   filename:  commands/permission/revoke-workspace-invitation.json

from __future__ import annotations

from enum import Enum
from uuid import UUID

from pydantic import AwareDatetime, BaseModel, ConfigDict, Field


class RevokeWorkspaceInvitation(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    workspaceId: UUID = Field(..., title="WorkspaceId")
    invitationId: UUID = Field(..., title="InvitationId")


class State(Enum):
    Expired = "Expired"
    Revoked = "Revoked"


class RevokeWorkspaceInvitationResponse(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    invitationId: UUID = Field(..., title="InvitationId")
    state: State
    expiresAt: AwareDatetime
