# generated by datamodel-codegen:
#   filename:  commands/permission/set-resource-permission.json

from __future__ import annotations

from enum import Enum
from uuid import UUID

from pydantic import AwareDatetime, BaseModel, ConfigDict, Field


class Role(Enum):
    Owner = "Owner"
    Manage = "Manage"
    Edit = "Edit"
    Comment = "Comment"
    Read = "Read"


class SetResourcePermission(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    resourceId: UUID = Field(..., title="ResourceId")
    accountId: UUID = Field(..., title="UserId")
    role: Role


class SetResourcePermissionResponse(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    resourceId: UUID = Field(..., title="ResourceId")
    accountId: UUID = Field(..., title="UserId")
    email: str
    role: Role
    createdAt: AwareDatetime
    updatedAt: AwareDatetime
