# generated by datamodel-codegen:
#   filename:  commands/permission/set-resource-share-link-expiry.json

from __future__ import annotations

from pydantic import AwareDatetime, BaseModel, ConfigDict

from ...queries.permission import list_resource_share_links


class SetResourceShareLinkExpiry(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    expiresAt: AwareDatetime | None


class SetResourceShareLinkExpiryResponse(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    shareLink: list_resource_share_links.ShareLinkMetadata
