# generated by datamodel-codegen:
#   filename:  commands/permission/transfer-workspace-owner.json

from __future__ import annotations

from typing import Literal
from uuid import UUID

from pydantic import AwareDatetime, BaseModel, ConfigDict, Field


class TransferWorkspaceOwner(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    workspaceId: UUID = Field(..., title="WorkspaceId")
    newOwnerAccountId: UUID = Field(..., title="UserId")
    idempotencyKey: UUID = Field(..., title="IdempotencyKey")


class TransferWorkspaceOwnerResponse(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    workspaceId: UUID = Field(..., title="WorkspaceId")
    previousOwnerAccountId: UUID = Field(..., title="UserId")
    newOwnerAccountId: UUID = Field(..., title="UserId")
    previousOwnerRemainsMember: Literal[True]
    independentProjectOwnerRowsChanged: Literal[False]
    transferredAt: AwareDatetime
