# generated by datamodel-codegen:
#   filename:  commands/tasks/cancel-task.json

from __future__ import annotations

from pydantic import BaseModel, ConfigDict

from ...queries.tasks import list_tasks


class CancelTaskResponse(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    task: list_tasks.TaskSummary
