# generated by datamodel-codegen:
#   filename:  queries/comments/list-comments.json

from __future__ import annotations

from typing import Any
from uuid import UUID

from pydantic import AwareDatetime, BaseModel, ConfigDict, Field


class Item(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    commentId: UUID = Field(..., title="UserId")
    threadId: UUID = Field(..., title="WorkspaceId")
    authorAccountId: UUID = Field(..., title="UserId")
    body: str
    anchor: dict[str, Any]
    createdAt: AwareDatetime


class ListCommentsResponse(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    resourceId: UUID = Field(..., title="UserId")
    items: list[Item]
