# generated by datamodel-codegen:
#   filename:  commands/importexport/create-resource-export-task.json

from __future__ import annotations

from uuid import UUID

from pydantic import BaseModel, ConfigDict, Field

from ...queries.tasks import list_tasks


class CreateResourceExportTaskResponse(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    taskId: UUID = Field(..., title="TaskId")
    exportSessionId: UUID = Field(..., title="SessionId")
    task: list_tasks.TaskSummary
