# generated by datamodel-codegen:
#   filename:  commands/importexport/import-resource.json

from __future__ import annotations

from typing import Any
from uuid import UUID

from pydantic import BaseModel, ConfigDict, Field


class ImportResource(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    resourceId: UUID = Field(..., title="UserId")
    document: dict[str, Any]
    idempotencyKey: UUID = Field(..., title="IdempotencyKey")


class ImportResourceResponse(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    resourceId: UUID = Field(..., title="UserId")
    journalSeq: int
