# generated by datamodel-codegen:
#   filename:  commands/importexport/import-resource.json

from __future__ import annotations

from uuid import UUID

from pydantic import BaseModel, ConfigDict, Field

from ...queries.importexport import export_resource
from ...queries.tasks import list_tasks


class ImportResource(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    resourceId: UUID = Field(..., title="ResourceId")
    document: export_resource.ExportResourceResponse
    idempotencyKey: UUID = Field(..., title="IdempotencyKey")


class ImportResourceResponse(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    taskId: UUID = Field(..., title="TaskId")
    task: list_tasks.TaskSummary
