# generated by datamodel-codegen:
#   filename:  commands/comments/add-comment.json

from __future__ import annotations

from typing import Any
from uuid import UUID

from pydantic import AwareDatetime, BaseModel, ConfigDict, Field, constr


class AddComment(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    resourceId: UUID = Field(..., title="UserId")
    threadId: UUID | None = Field(None, title="WorkspaceId")
    body: constr(min_length=1)
    anchor: dict[str, Any] | None = None
    idempotencyKey: UUID = Field(..., title="IdempotencyKey")


class AddCommentResponse(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    commentId: UUID = Field(..., title="UserId")
    threadId: UUID = Field(..., title="WorkspaceId")
    body: str
    createdAt: AwareDatetime
