# generated by datamodel-codegen:
#   filename:  commands/comments/delete-comment.json

from __future__ import annotations

from typing import Literal
from uuid import UUID

from pydantic import BaseModel, ConfigDict, Field


class DeleteComment(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    commentId: UUID = Field(..., title="UserId")
    idempotencyKey: UUID = Field(..., title="IdempotencyKey")


class DeleteCommentResponse(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    commentId: UUID = Field(..., title="UserId")
    deleted: Literal[True]
