# generated by datamodel-codegen:
#   filename:  commands/comments/edit-comment.json

from __future__ import annotations

from uuid import UUID

from pydantic import BaseModel, ConfigDict, Field, constr


class EditComment(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    commentId: UUID = Field(..., title="CommentId")
    body: constr(min_length=1)
    idempotencyKey: UUID = Field(..., title="IdempotencyKey")


class EditCommentResponse(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    commentId: UUID = Field(..., title="CommentId")
    body: str
