# generated by datamodel-codegen:
#   filename:  commands/comments/reopen-comment-thread.json

from __future__ import annotations

from typing import Literal
from uuid import UUID

from pydantic import BaseModel, ConfigDict, Field


class ReopenCommentThreadResponse(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    threadId: UUID = Field(..., title="ThreadId")
    resourceId: UUID = Field(..., title="ResourceId")
    status: Literal["Open"]
    resolvedAt: None
    resolvedBy: None
