# generated by datamodel-codegen:
#   filename:  commands/comments/resolve-comment-thread.json

from __future__ import annotations

from typing import Literal
from uuid import UUID

from pydantic import AwareDatetime, BaseModel, ConfigDict, Field


class ResolveCommentThreadResponse(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    threadId: UUID = Field(..., title="ThreadId")
    resourceId: UUID = Field(..., title="ResourceId")
    status: Literal["Resolved"]
    resolvedAt: AwareDatetime
    resolvedBy: UUID = Field(..., title="UserId")
