# generated by datamodel-codegen:
#   filename:  queries/workspace/get-project-tree.json

from __future__ import annotations

from enum import Enum
from uuid import UUID

from pydantic import BaseModel, ConfigDict, Field


class ProjectLifecycle(Enum):
    Active = "Active"
    Archived = "Archived"
    Trashed = "Trashed"
    Purging = "Purging"
    Purged = "Purged"


class FolderLifecycle(Enum):
    Active = "Active"
    Trashed = "Trashed"
    Deleted = "Deleted"


class ProjectSummary(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    name: str
    lifecycle: ProjectLifecycle


class FolderSummary(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    folderId: UUID = Field(..., title="FolderId")
    parentFolderId: UUID | None
    name: str
    lifecycle: FolderLifecycle
    hasChildren: bool


class GetProjectTreeResponse(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    workspaceId: UUID = Field(..., title="WorkspaceId")
    projectId: UUID = Field(..., title="ProjectId")
    project: ProjectSummary
    folders: list[FolderSummary]
    nextCursor: str | None
