# generated by datamodel-codegen:
#   filename:  queries/workspace/get-workspace.json

from __future__ import annotations

from enum import Enum
from uuid import UUID

from pydantic import AwareDatetime, BaseModel, ConfigDict, Field


class Lifecycle(Enum):
    Active = "Active"
    DeletionPending = "DeletionPending"
    Deleted = "Deleted"


class GetWorkspaceResponse(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    workspaceId: UUID = Field(..., title="WorkspaceId")
    name: str
    ownerAccountId: UUID = Field(..., title="UserId")
    lifecycle: Lifecycle
    createdAt: AwareDatetime
    updatedAt: AwareDatetime
