# generated by datamodel-codegen:
#   filename:  queries/workspace/list-folder-children.json

from __future__ import annotations

from enum import Enum
from uuid import UUID

from pydantic import BaseModel, ConfigDict, Field


class Lifecycle(Enum):
    Active = "Active"
    Trashed = "Trashed"
    Deleted = "Deleted"


class FolderSummary(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    folderId: UUID = Field(..., title="FolderId")
    name: str
    lifecycle: Lifecycle
    hasChildren: bool


class ListFolderChildrenResponse(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    projectId: UUID = Field(..., title="ProjectId")
    parentFolderId: UUID | None
    items: list[FolderSummary]
    nextCursor: str | None
