# generated by datamodel-codegen:
#   filename:  queries/workspace/list-workspaces.json

from __future__ import annotations

from enum import Enum
from uuid import UUID

from pydantic import AwareDatetime, BaseModel, ConfigDict, Field


class MembershipKind(Enum):
    Owner = "Owner"
    Member = "Member"


class Lifecycle(Enum):
    Active = "Active"
    DeletionPending = "DeletionPending"
    Deleted = "Deleted"


class Workspace(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    workspaceId: UUID = Field(..., title="WorkspaceId")
    name: str
    membershipKind: MembershipKind
    lifecycle: Lifecycle
    createdAt: AwareDatetime


class ListWorkspacesResponse(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    workspaces: list[Workspace]
