# generated by datamodel-codegen:
#   filename:  queries/workspace/list-projects.json

from __future__ import annotations

from enum import Enum
from uuid import UUID

from pydantic import AwareDatetime, BaseModel, ConfigDict, Field


class Lifecycle(Enum):
    Active = "Active"
    Archived = "Archived"
    Trashed = "Trashed"
    Purging = "Purging"
    Purged = "Purged"


class ProjectSummary(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    projectId: UUID = Field(..., title="ProjectId")
    workspaceId: UUID = Field(..., title="WorkspaceId")
    name: str
    lifecycle: Lifecycle
    updatedAt: AwareDatetime


class ListProjectsResponse(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    workspaceId: UUID = Field(..., title="WorkspaceId")
    items: list[ProjectSummary]
    nextCursor: str | None
