# generated by datamodel-codegen:
#   filename:  queries/workspace/member-suggestions.json

from __future__ import annotations

from uuid import UUID

from pydantic import BaseModel, ConfigDict, Field


class Suggestion(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    accountId: UUID = Field(..., title="UserId")
    email: str


class SuggestMembersResponse(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    workspaceId: UUID = Field(..., title="WorkspaceId")
    suggestions: list[Suggestion]
