# generated by datamodel-codegen:
#   filename:  commands/resource/append-journal-op.json

from __future__ import annotations

from uuid import UUID

from pydantic import BaseModel, ConfigDict, Field, conint, constr


class AppendJournalOp(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    resourceId: UUID = Field(..., title="UserId")
    expectedSeq: conint(ge=1) | None = None
    update: constr(min_length=1) = Field(
        ..., json_schema_extra={"contentEncoding": "base64"}
    )
    idempotencyKey: UUID = Field(..., title="IdempotencyKey")


class AppendJournalOpResponse(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    resourceId: UUID = Field(..., title="UserId")
    journalSeq: int
    updateSha256: str
    acceptedWatermark: conint(ge=0)
    durableWatermark: conint(ge=0)
