# generated by datamodel-codegen:
#   filename:  commands/resource/create-resource.json

from __future__ import annotations

from enum import Enum
from uuid import UUID

from pydantic import AwareDatetime, BaseModel, ConfigDict, Field, constr


class ResourceType(Enum):
    document = "document"
    code = "code"
    markdown = "markdown"
    text = "text"


class Lifecycle(Enum):
    Active = "Active"
    Trashed = "Trashed"
    Purging = "Purging"
    Purged = "Purged"


class CreateResource(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    projectId: UUID = Field(..., title="WorkspaceId")
    folderId: UUID | None = None
    resourceType: ResourceType
    name: constr(min_length=1, max_length=200)
    idempotencyKey: UUID = Field(..., title="IdempotencyKey")


class CreateResourceResponse(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    resourceId: UUID = Field(..., title="UserId")
    projectId: UUID = Field(..., title="WorkspaceId")
    folderId: UUID | None = None
    resourceType: ResourceType
    name: str
    lifecycle: Lifecycle
    createdAt: AwareDatetime
