# generated by datamodel-codegen:
#   filename:  commands/resource/rename-resource.json

from __future__ import annotations

from uuid import UUID

from pydantic import BaseModel, ConfigDict, Field, constr


class RenameResource(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    resourceId: UUID = Field(..., title="UserId")
    name: constr(min_length=1, max_length=200)
    idempotencyKey: UUID = Field(..., title="IdempotencyKey")


class RenameResourceResponse(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    resourceId: UUID = Field(..., title="UserId")
    name: str
