# generated by datamodel-codegen:
#   filename:  commands/resource/replace-resource-content.json

from __future__ import annotations

from enum import Enum
from uuid import UUID

from pydantic import BaseModel, ConfigDict, Field, conint

from ...queries.resource import open_resource


class Reason(Enum):
    import_ = "import"
    history_restore = "history-restore"
    ai_changeset = "ai-changeset"


class ReplaceResourceContent(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    resourceId: UUID = Field(..., title="ResourceId")
    operationId: UUID = Field(..., title="IdempotencyKey")
    expectedJournalSeq: conint(ge=0) | None = None
    createdBy: UUID | None
    reason: Reason
    restoreTargetSeq: conint(ge=1) | None = None
    snapshot: open_resource.ContentSnapshot


class ReplaceResourceContentResponse(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    resourceId: UUID = Field(..., title="ResourceId")
    journalSeq: conint(ge=1)
