# generated by datamodel-codegen:
#   filename:  commands/resource/trash-resource.json

from __future__ import annotations

from enum import Enum
from uuid import UUID

from pydantic import BaseModel, ConfigDict, Field


class TrashResource(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    resourceId: UUID = Field(..., title="UserId")
    idempotencyKey: UUID = Field(..., title="IdempotencyKey")


class Lifecycle(Enum):
    Active = "Active"
    Trashed = "Trashed"
    Purging = "Purging"
    Purged = "Purged"


class TrashResourceResponse(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    resourceId: UUID = Field(..., title="UserId")
    lifecycle: Lifecycle
