# generated by datamodel-codegen:
#   filename:  events/workspace/folder-renamed.json

from __future__ import annotations

from typing import Literal
from uuid import UUID

from pydantic import AwareDatetime, BaseModel, ConfigDict, Field, constr


class FolderRenamedPayload(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    workspaceId: UUID = Field(..., title="WorkspaceId")
    projectId: UUID = Field(..., title="ProjectId")
    folderId: UUID = Field(..., title="FolderId")
    previousName: str
    name: str
    actorAccountId: UUID = Field(..., title="UserId")


class FolderRenamed(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    eventId: UUID = Field(..., title="EventId")
    eventType: Literal["FolderRenamed"]
    schemaVersion: constr(pattern=r"^\d+\.\d+\.\d+$")
    occurredAt: AwareDatetime
    producer: constr(min_length=1)
    payload: FolderRenamedPayload
