# generated by datamodel-codegen:
#   filename:  events/workspace/project-archived.json

from __future__ import annotations

from typing import Literal
from uuid import UUID

from pydantic import AwareDatetime, BaseModel, ConfigDict, Field, constr


class ProjectArchivedPayload(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    workspaceId: UUID = Field(..., title="WorkspaceId")
    projectId: UUID = Field(..., title="ProjectId")
    actorAccountId: UUID = Field(..., title="UserId")


class ProjectArchived(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    eventId: UUID = Field(..., title="EventId")
    eventType: Literal["ProjectArchived"]
    schemaVersion: constr(pattern=r"^\d+\.\d+\.\d+$")
    occurredAt: AwareDatetime
    producer: constr(min_length=1)
    payload: ProjectArchivedPayload
