# generated by datamodel-codegen:
#   filename:  events/workspace/workspace-created.json

from __future__ import annotations

from typing import Literal
from uuid import UUID

from pydantic import AwareDatetime, BaseModel, ConfigDict, Field, constr


class WorkspaceCreatedPayload(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    workspaceId: UUID = Field(..., title="WorkspaceId")
    actorAccountId: UUID = Field(..., title="UserId")
    name: str


class WorkspaceCreated(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    eventId: UUID = Field(..., title="EventId")
    eventType: Literal["WorkspaceCreated"]
    schemaVersion: constr(pattern=r"^\d+\.\d+\.\d+$")
    occurredAt: AwareDatetime
    producer: constr(min_length=1)
    traceId: UUID | None = Field(None, title="RequestId")
    payload: WorkspaceCreatedPayload
