# generated by datamodel-codegen:
#   filename:  queries/auth/get-current-session.json

from __future__ import annotations

from uuid import UUID

from pydantic import AwareDatetime, BaseModel, ConfigDict, Field

from ...ids import ids


class GetCurrentSessionResponse(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    sessionId: UUID = Field(..., title="SessionId")
    createdAt: AwareDatetime
    lastSeenAt: AwareDatetime
    expiresAt: AwareDatetime
    currentDevice: bool
    status: ids.SessionStatusValue
    lastStrongAuthAt: AwareDatetime | None = None
