# generated by datamodel-codegen:
#   filename:  queries/auth/get-current-account.json

from __future__ import annotations

from uuid import UUID

from pydantic import AwareDatetime, BaseModel, ConfigDict, EmailStr, Field

from ...ids import ids


class GetCurrentAccountResponse(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    accountId: UUID = Field(..., title="UserId")
    primaryEmail: EmailStr
    accountStatus: ids.AccountStatusValue
    emailVerifiedAt: AwareDatetime | None
    createdAt: AwareDatetime
    canCreateWorkspace: bool
    inAccountRecoveryMode: bool
