# generated by datamodel-codegen:
#   filename:  queries/auth/get-account-status.json

from __future__ import annotations

from pydantic import AwareDatetime, BaseModel, ConfigDict

from ...ids import ids


class GetAccountStatusResponse(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    accountStatus: ids.AccountStatusValue
    inAccountRecoveryMode: bool
    deletionRequestedAt: AwareDatetime | None
    gracePeriodDaysRemaining: int | None
    executeAfter: AwareDatetime | None
    canCancelDeletion: bool
